// Package layout is selfdoc's declaration of the per-repository directories it
// owns, and the single authority for every path it reads or writes inside them.
//
// A repository keeps one hidden directory at its root, [Root], holding
// function-named directories rather than tool-named ones: docs/ is the pages a
// person writes, docs-state/ is what selfdoc generates and the repository
// commits, docs-cache/ is what selfdoc generates and the repository does not
// commit, posts/ is the blog, vocabulary/ is the project's word lists. Another
// tool's state lives beside them under its own function name.
//
// # Ownership
//
// Every directory under [Root] has exactly one owner tool, declared in
// [OwnersFileName]. A row is the permission to create: [EnsureDir] refuses to
// create a directory no row assigns to selfdoc, naming the row to add. Reading
// and writing are open to anyone; the owner decides whether what was written is
// acceptable, which is what [Validate] answers.
//
// # Sides
//
// A directory is entirely handwritten or entirely generated -- never both. The
// side is a property of the function, so it is declared here once rather than
// per repository, and [Validate] holds the tree to it: a generated page in a
// handwritten directory, or a handwritten page in a generated one, is a defect
// with a named remedy.
//
// # The derived ignore file
//
// git needs one file inside [Root] to keep the uncommitted directories out of
// the repository. It is derived, at [Root]/[IgnoreFileName], from the
// commitment each tool declares. selfdoc owns only the block between its two
// marker comments and leaves every other line of that file alone, so several
// tools can write their own blocks into one file.
package layout

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/smm-h/selfdoc/internal/effects"
)

// Root is the one hidden directory a repository's tool-owned state lives in,
// relative to the repository root.
const Root = ".stricttools"

// Owner is the name selfdoc is declared under in the owners file.
const Owner = "selfdoc"

// OwnersFileName is the ownership declaration inside [Root].
const OwnersFileName = "OWNERS.csv"

// OwnersHeader is the first line every owners file carries. The file is read
// with a header, always, so a reader never has to guess whether its first line
// is a row.
const OwnersHeader = "directory,owner"

// IgnoreFileName is the derived ignore file inside [Root], and the one entry
// there allowed to start with a dot.
const IgnoreFileName = ".gitignore"

// MoveScript is the script that moves a repository off the layout selfdoc used
// before this one. Every refusal of the old layout names it.
const MoveScript = "scripts/move-to-stricttools-layout.py"

// GeneratedMarkerPrefix opens the HTML comment every page selfdoc generates
// carries under its frontmatter. It is what tells a generated page from a
// handwritten one on disk, which is how [Validate] checks a directory's side.
const GeneratedMarkerPrefix = "<!-- generated by selfdoc gen"

// Side is whether a directory's contents are written by a person or by a tool.
type Side string

// The two sides. A directory is entirely one or entirely the other.
const (
	Handwritten Side = "handwritten"
	Generated   Side = "generated"
)

// Commitment is whether a directory's contents belong in the repository.
type Commitment string

// The two commitments. An uncommitted directory contributes one line to the
// derived ignore file.
const (
	Committed   Commitment = "committed"
	Uncommitted Commitment = "uncommitted"
)

// The names of the function directories selfdoc claims, relative to [Root].
const (
	DocsName       = "docs"
	DocsStateName  = "docs-state"
	DocsCacheName  = "docs-cache"
	PostsName      = "posts"
	VocabularyName = "vocabulary"
)

// The function directories, as paths relative to the repository root, in slash
// form.
const (
	DocsRel       = Root + "/" + DocsName
	DocsStateRel  = Root + "/" + DocsStateName
	DocsCacheRel  = Root + "/" + DocsCacheName
	PostsRel      = Root + "/" + PostsName
	VocabularyRel = Root + "/" + VocabularyName
)

// The files and subdirectories selfdoc keeps inside its function directories,
// as paths relative to the repository root, in slash form.
const (
	// GeneratedPagesRel is the second docs root: the pages selfdoc generates,
	// merged into one URL namespace with the handwritten root at build time.
	GeneratedPagesRel = DocsStateRel + "/pages"
	// ManifestRel is the record of what a build published.
	ManifestRel = DocsStateRel + "/manifest.json"
	// PostManifestRel is the posts-only manifest the assembly's post publisher
	// reads.
	PostManifestRel = DocsStateRel + "/post-manifest.json"
	// RevisionsRel is the post revision sidecar.
	RevisionsRel = DocsStateRel + "/revisions.json"
	// HashesDirRel holds the content and description hash baselines.
	HashesDirRel = DocsStateRel + "/hashes"
	// HashesRel is the hash store itself.
	HashesRel = HashesDirRel + "/hashes.json"
	// DataRel is where a sandboxed gen-data script writes its output.
	DataRel = DocsStateRel + "/data"
	// OutputRel is the built site.
	OutputRel = DocsCacheRel + "/build"
	// VersionsRel holds one extracted checkout per archived version.
	VersionsRel = DocsCacheRel + "/versions"
)

// The declared values of the config keys that name a layout directory. A
// project that declares nothing gets these, and a project that declares
// something else has to keep it under [Root].
const (
	DocsDefault   = DocsRel + "/"
	OutputDefault = OutputRel + "/"
	PostsDefault  = PostsRel + "/"
)

// Directory is one function directory selfdoc claims: what it is for, which
// side of the authorship line it sits on, whether the repository commits it,
// and the paths it replaced.
type Directory struct {
	// Name is the directory's name under [Root].
	Name string
	// Side is whether people or selfdoc write its contents.
	Side Side
	// Commitment is whether the repository carries its contents.
	Commitment Commitment
	// Description says what the directory holds.
	Description string
	// DeprecatedNames are the paths this directory replaced, as they were
	// spelled relative to the repository root. A repository that still has
	// one of them is refused.
	DeprecatedNames []string
	// CreatedByTool is whether selfdoc creates this directory itself once a
	// row permits it. A directory it never creates is one whose content a
	// person writes first, so its row is added when that content arrives:
	// git carries no empty directory, and a row naming one that does not
	// exist fails [Validate].
	CreatedByTool bool
}

// declared is the whole claim, in the order a dump prints it.
var declared = []Directory{
	{
		Name:            DocsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The pages a person writes, the underscore-prefixed templates they include, and the docs configuration that sits beside them.",
		DeprecatedNames: []string{"docs/"},
		CreatedByTool:   true,
	},
	{
		Name:            DocsStateName,
		Side:            Generated,
		Commitment:      Committed,
		Description:     "What selfdoc generates and the repository keeps: the manifests, the hash baselines, the post revisions, the generated data files, and the generated pages.",
		DeprecatedNames: []string{".selfdoc/"},
		CreatedByTool:   true,
	},
	{
		Name:            DocsCacheName,
		Side:            Generated,
		Commitment:      Uncommitted,
		Description:     "What selfdoc generates and the repository throws away: the built site and one extracted checkout per archived version.",
		DeprecatedNames: []string{"docs/_build/", ".selfdoc/cache/"},
		CreatedByTool:   true,
	},
	{
		Name:            PostsName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's blog posts.",
		DeprecatedNames: []string{".selfdoc/posts/"},
		CreatedByTool:   true,
	},
	{
		Name:            VocabularyName,
		Side:            Handwritten,
		Commitment:      Committed,
		Description:     "The project's accepted and rejected vocabulary, read by the spell check and the glossary.",
		DeprecatedNames: nil,
	},
}

// Declared returns the directories selfdoc claims, in declaration order.
func Declared() []Directory {
	out := make([]Directory, len(declared))
	copy(out, declared)
	return out
}

// Lookup returns the declaration of one claimed directory.
func Lookup(name string) (Directory, bool) {
	for _, dir := range declared {
		if dir.Name == name {
			return dir, true
		}
	}
	return Directory{}, false
}

// Path joins a repository root with one of this package's slash-form relative
// paths, in the operating system's own spelling.
func Path(baseDir, rel string) string {
	return filepath.Join(baseDir, filepath.FromSlash(rel))
}

// UnderRoot reports whether a declared path names something inside [Root].
// A project may spell its docs and output paths as it likes as long as they
// live in the layout.
func UnderRoot(declaredPath string) bool {
	clean := path.Clean(strings.TrimRight(filepath.ToSlash(declaredPath), "/"))
	return clean == Root || strings.HasPrefix(clean, Root+"/")
}

// FunctionOf returns the function directory a relative path sits in.
func FunctionOf(rel string) (string, bool) {
	clean := strings.TrimRight(filepath.ToSlash(rel), "/")
	if !strings.HasPrefix(clean, Root+"/") {
		return "", false
	}
	rest := strings.TrimPrefix(clean, Root+"/")
	if rest == "" {
		return "", false
	}
	return strings.SplitN(rest, "/", 2)[0], true
}

// RequiredRows is the owners file a repository needs for selfdoc, header
// first, one row per directory selfdoc creates itself. Every refusal that asks
// for rows prints from here, so the text a person is told to paste is generated
// from the claim rather than typed beside it.
//
// A directory selfdoc does not create is left out: its row is added when its
// content is, because git carries no empty directory and [Validate] fails a row
// naming a directory that does not exist.
func RequiredRows() []string {
	rows := []string{OwnersHeader}
	for _, dir := range declared {
		if dir.CreatedByTool {
			rows = append(rows, dir.Name+","+Owner)
		}
	}
	return rows
}

// Owners is a repository's ownership declaration: which tool owns each
// directory under [Root].
type Owners struct {
	// Order is the directory names in the order the file declares them.
	Order []string
	// Owner maps a directory name to the tool that owns it.
	Owner map[string]string
	// Path is the file this was read from.
	Path string
}

// OwnersPath is where a repository's ownership declaration sits.
func OwnersPath(baseDir string) string {
	return Path(baseDir, Root+"/"+OwnersFileName)
}

// ReadOwners reads a repository's ownership declaration.
//
// A missing [Root], a missing owners file, a missing or wrong header, a row
// that is not two fields, and a directory named twice are each an error whose
// message names the remedy.
func ReadOwners(baseDir string) (*Owners, error) {
	ownersPath := OwnersPath(baseDir)
	content, err := os.ReadFile(ownersPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf(
				"%s is missing. selfdoc never creates it: make the directory and write the file yourself, with these lines:\n%s",
				filepath.Join(Root, OwnersFileName), strings.Join(RequiredRows(), "\n"))
		}
		return nil, err
	}
	owners := &Owners{Owner: map[string]string{}, Path: ownersPath}
	lines := strings.Split(strings.ReplaceAll(string(content), "\r\n", "\n"), "\n")
	seenHeader := false
	for number, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if !seenHeader {
			if trimmed != OwnersHeader {
				return nil, fmt.Errorf(
					"%s line %d: the first line must be the header %q, not %q",
					ownersPath, number+1, OwnersHeader, trimmed)
			}
			seenHeader = true
			continue
		}
		fields := strings.Split(trimmed, ",")
		if len(fields) != 2 {
			return nil, fmt.Errorf(
				"%s line %d: a row is two comma-separated fields, %q; got %q",
				ownersPath, number+1, OwnersHeader, trimmed)
		}
		name := strings.TrimSpace(fields[0])
		tool := strings.TrimSpace(fields[1])
		if name == "" || tool == "" {
			return nil, fmt.Errorf(
				"%s line %d: both the directory and the owner must be named; got %q",
				ownersPath, number+1, trimmed)
		}
		if _, exists := owners.Owner[name]; exists {
			return nil, fmt.Errorf(
				"%s line %d: directory %q is declared twice; one directory has one owner",
				ownersPath, number+1, name)
		}
		owners.Owner[name] = tool
		owners.Order = append(owners.Order, name)
	}
	if !seenHeader {
		return nil, fmt.Errorf("%s is empty; its first line must be the header %q",
			ownersPath, OwnersHeader)
	}
	return owners, nil
}

// EnsureOwned answers whether selfdoc may create one of its function
// directories in this repository.
//
// The row is the permission. A repository with no row for the directory, or a
// row naming another tool, is refused with the row to add.
func EnsureOwned(baseDir, name string) error {
	owners, err := ReadOwners(baseDir)
	if err != nil {
		return err
	}
	tool, declared := owners.Owner[name]
	if !declared {
		return fmt.Errorf(
			"selfdoc may not create %s: no row in %s names an owner for it. Add this row:\n%s",
			filepath.Join(Root, name), owners.Path, name+","+Owner)
	}
	if tool != Owner {
		return fmt.Errorf(
			"selfdoc may not create %s: %s declares %q as its owner, not %q",
			filepath.Join(Root, name), owners.Path, tool, Owner)
	}
	return nil
}

// EnsureDir creates a directory inside one of selfdoc's function directories,
// after checking the row that permits it, and refreshes the derived ignore
// file.
//
// rel is one of this package's slash-form relative paths. Creating anything
// under [Root] goes through here, so no path can reach the filesystem without
// its owning row having been checked.
func EnsureDir(h *effects.Handle, baseDir, rel string) error {
	name, ok := FunctionOf(rel)
	if !ok {
		return fmt.Errorf("%q is not a path under %s", rel, Root)
	}
	if _, claimed := Lookup(name); !claimed {
		return fmt.Errorf("selfdoc does not claim %s", filepath.Join(Root, name))
	}
	if err := EnsureOwned(baseDir, name); err != nil {
		return err
	}
	if err := h.MkdirAll(Path(baseDir, rel)); err != nil {
		return err
	}
	return WriteIgnore(h, baseDir)
}

// The comments selfdoc's block of the derived ignore file sits between. Lines
// outside them belong to other tools and are left as they stand.
const (
	ignoreBegin = "# BEGIN selfdoc -- derived from selfdoc's layout declaration"
	ignoreEnd   = "# END selfdoc"
)

// IgnoreBlock is selfdoc's block of the derived ignore file: the marker
// comments around one line per uncommitted directory it owns.
func IgnoreBlock() []string {
	block := []string{ignoreBegin}
	for _, dir := range declared {
		if dir.Commitment == Uncommitted {
			block = append(block, dir.Name+"/")
		}
	}
	return append(block, ignoreEnd)
}

// RenderIgnore returns what the derived ignore file should hold, given what it
// holds now: selfdoc's block replaced in place, or appended when the file
// carries none, with every other line untouched.
func RenderIgnore(existing string) string {
	block := IgnoreBlock()
	var before, after []string
	inBlock, sawBlock := false, false
	for _, line := range strings.Split(strings.ReplaceAll(existing, "\r\n", "\n"), "\n") {
		switch {
		case strings.TrimSpace(line) == ignoreBegin:
			inBlock, sawBlock = true, true
		case strings.TrimSpace(line) == ignoreEnd:
			inBlock = false
		case inBlock:
			// A line inside selfdoc's own block is replaced by the block.
		case sawBlock:
			after = append(after, line)
		default:
			before = append(before, line)
		}
	}
	lines := append([]string{}, trimBlankEdges(before)...)
	if len(lines) > 0 {
		lines = append(lines, "")
	}
	lines = append(lines, block...)
	if rest := trimBlankEdges(after); len(rest) > 0 {
		lines = append(lines, "")
		lines = append(lines, rest...)
	}
	return strings.Join(lines, "\n") + "\n"
}

// trimBlankEdges drops the blank lines at both ends of a slice, so joining
// sections never doubles a blank line.
func trimBlankEdges(lines []string) []string {
	start, end := 0, len(lines)
	for start < end && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return lines[start:end]
}

// IgnorePath is where the derived ignore file sits.
func IgnorePath(baseDir string) string {
	return Path(baseDir, Root+"/"+IgnoreFileName)
}

// WriteIgnore brings the derived ignore file up to date, writing nothing when
// it already holds what it should.
func WriteIgnore(h *effects.Handle, baseDir string) error {
	target := IgnorePath(baseDir)
	existing, err := os.ReadFile(target)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	wanted := RenderIgnore(string(existing))
	if string(existing) == wanted {
		return nil
	}
	return h.AtomicWrite(target, []byte(wanted), effects.ModeDefault)
}

// IgnoreIsCurrent reports whether the derived ignore file holds selfdoc's block
// as declared, and returns the content it should hold.
func IgnoreIsCurrent(baseDir string) (bool, string) {
	existing, err := os.ReadFile(IgnorePath(baseDir))
	if err != nil {
		existing = nil
	}
	wanted := RenderIgnore(string(existing))
	return string(existing) == wanted, wanted
}
