"""Tests for selfdoc.gen.generate_root_files -- root file generation."""

import json
import os
import stat

import pytest

from selfdoc.gen import generate_root_files


def _make_config(tmp_path, root_files=None, extras=None):
    """Create a minimal selfdoc.json and source tree, return config dict."""
    lib_dir = os.path.join(tmp_path, "mylib")
    os.makedirs(lib_dir, exist_ok=True)
    with open(os.path.join(lib_dir, "__init__.py"), "w") as f:
        f.write('"""My library."""\n')

    os.makedirs(os.path.join(tmp_path, "docs"), exist_ok=True)

    config = {
        "source": [{"path": "mylib/", "language": "python"}],
        "docs": "docs/",
        "output": "docs/_build/",
    }
    if root_files is not None:
        config["root_files"] = root_files
    if extras:
        config.update(extras)

    config_path = os.path.join(tmp_path, "selfdoc.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f)

    return config


class TestNoRootFilesConfig:
    """Empty or missing root_files returns empty list."""

    def test_no_root_files_key(self, tmp_path):
        config = _make_config(tmp_path)
        result = generate_root_files(config, base_dir=str(tmp_path))
        assert result == []

    def test_empty_root_files_list(self, tmp_path):
        config = _make_config(tmp_path, root_files=[])
        result = generate_root_files(config, base_dir=str(tmp_path))
        assert result == []


class TestGenerateRootFile:
    """Generate a root file from a template with a directive."""

    def test_generates_output(self, tmp_path):
        template_content = (
            "---\n"
            "title: Test\n"
            "---\n"
            "# Hello\n"
            "\n"
            "Some text.\n"
        )
        template_path = os.path.join(tmp_path, "docs", "_TEST.md")
        os.makedirs(os.path.join(tmp_path, "docs"), exist_ok=True)
        with open(template_path, "w", encoding="utf-8") as f:
            f.write(template_content)

        config = _make_config(tmp_path, root_files=["docs/_TEST.md"])
        result = generate_root_files(config, base_dir=str(tmp_path))

        assert result == ["TEST.md"]
        output_path = os.path.join(tmp_path, "TEST.md")
        assert os.path.isfile(output_path)

        with open(output_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Header present
        assert content.startswith(
            "<!-- Auto-generated by selfdoc from docs/_TEST.md"
        )
        # Frontmatter stripped
        assert "title: Test" not in content
        # Body content preserved
        assert "# Hello" in content
        assert "Some text." in content

    def test_output_permissions(self, tmp_path):
        template_path = os.path.join(tmp_path, "docs", "_PERM.md")
        os.makedirs(os.path.join(tmp_path, "docs"), exist_ok=True)
        with open(template_path, "w", encoding="utf-8") as f:
            f.write("# Permissions test\n")

        config = _make_config(tmp_path, root_files=["docs/_PERM.md"])
        generate_root_files(config, base_dir=str(tmp_path))

        output_path = os.path.join(tmp_path, "PERM.md")
        mode = os.stat(output_path).st_mode
        assert mode & 0o777 == 0o444


class TestRefusesOverwriteNonGenerated:
    """Refuse to overwrite a hand-written file without the header."""

    def test_raises_on_handwritten(self, tmp_path):
        # Create a hand-written TEST.md at the project root
        handwritten = os.path.join(tmp_path, "TEST.md")
        with open(handwritten, "w", encoding="utf-8") as f:
            f.write("# My hand-written file\n")

        template_path = os.path.join(tmp_path, "docs", "_TEST.md")
        os.makedirs(os.path.join(tmp_path, "docs"), exist_ok=True)
        with open(template_path, "w", encoding="utf-8") as f:
            f.write("# Template\n")

        config = _make_config(tmp_path, root_files=["docs/_TEST.md"])
        with pytest.raises(RuntimeError, match="Refusing to overwrite"):
            generate_root_files(config, base_dir=str(tmp_path))


class TestOverwritesExistingGenerated:
    """Overwrite an existing file that has the auto-generated header."""

    def test_overwrites_generated(self, tmp_path):
        output_path = os.path.join(tmp_path, "TEST.md")
        # Write an old generated version (with header, read-only)
        old_content = (
            "<!-- Auto-generated by selfdoc from docs/_TEST.md"
            " — do not edit -->\n\n"
            "# Old content\n"
        )
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(old_content)
        os.chmod(output_path, 0o444)

        template_path = os.path.join(tmp_path, "docs", "_TEST.md")
        os.makedirs(os.path.join(tmp_path, "docs"), exist_ok=True)
        with open(template_path, "w", encoding="utf-8") as f:
            f.write("# New content\n")

        config = _make_config(tmp_path, root_files=["docs/_TEST.md"])
        result = generate_root_files(config, base_dir=str(tmp_path))

        assert result == ["TEST.md"]
        with open(output_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "# New content" in content
        assert "# Old content" not in content


class TestMissingTemplate:
    """Error when a template path in root_files does not exist."""

    def test_raises_on_missing(self, tmp_path):
        config = _make_config(
            tmp_path, root_files=["docs/_NONEXISTENT.md"],
        )
        with pytest.raises(RuntimeError, match="template not found"):
            generate_root_files(config, base_dir=str(tmp_path))
