"""Tests for the SQL schema extractor (selfdoc.extractors.sql)."""

import os

import pytest

from selfdoc.extractors.sql import (
    SqlExtractor,
    _parse_comments,
    _parse_create_function,
    _parse_create_table,
    _parse_create_type,
    _parse_create_view,
)


@pytest.fixture()
def sql_project(tmp_path):
    """Create a sample SQL project structure for testing."""
    sql_dir = os.path.join(tmp_path, "sql")
    os.makedirs(sql_dir)

    # Main schema file with tables, comments, views, types, functions
    schema_sql = os.path.join(sql_dir, "schema.sql")
    with open(schema_sql, "w", encoding="utf-8") as f:
        f.write("""\
-- Main schema for the application

CREATE TABLE users (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    display_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id)
);

COMMENT ON TABLE users IS 'Registered user accounts';
COMMENT ON COLUMN users.id IS 'Unique user identifier';
COMMENT ON COLUMN users.email IS 'User email address, must be unique';
COMMENT ON COLUMN users.display_name IS 'Optional display name';

CREATE TABLE posts (
    id bigint GENERATED ALWAYS AS IDENTITY,
    author_id uuid NOT NULL REFERENCES users(id),
    title text NOT NULL,
    body text NOT NULL DEFAULT '',
    view_count integer NOT NULL DEFAULT 0,
    score numeric(10,2),
    tags text[],
    published_at timestamptz,
    CONSTRAINT posts_title_check CHECK (length(title) > 0)
);

COMMENT ON TABLE posts IS 'User-created blog posts';
COMMENT ON COLUMN posts.author_id IS 'Reference to the post author';
COMMENT ON COLUMN posts.tags IS 'Array of tag strings';

CREATE VIEW active_users AS
SELECT id, email, display_name
FROM users
WHERE is_active = true;

CREATE OR REPLACE VIEW recent_posts AS
SELECT p.id, p.title, u.display_name AS author
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.published_at > now() - interval '7 days';

CREATE TYPE status_type AS ENUM ('draft', 'published', 'archived');

CREATE TYPE address AS (
    street text,
    city text,
    zip_code text,
    country text
);

CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION soft_delete(target_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE users SET is_active = false WHERE id = target_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_timestamp IS 'Auto-update timestamp trigger function';
""")

    # File with schema-qualified names
    qualified_sql = os.path.join(sql_dir, "qualified.sql")
    with open(qualified_sql, "w", encoding="utf-8") as f:
        f.write("""\
CREATE TABLE public.sessions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.users(id),
    token text NOT NULL,
    expires_at timestamptz NOT NULL
);

COMMENT ON TABLE public.sessions IS 'Active user sessions';
COMMENT ON COLUMN public.sessions.token IS 'Session authentication token';

CREATE TABLE IF NOT EXISTS audit.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_type text NOT NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
""")

    # File with generated columns
    generated_sql = os.path.join(sql_dir, "generated.sql")
    with open(generated_sql, "w", encoding="utf-8") as f:
        f.write("""\
CREATE TABLE products (
    id bigint GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    price numeric(10,2) NOT NULL,
    tax_rate numeric(5,4) NOT NULL DEFAULT 0.0825,
    total_price numeric(10,2) GENERATED ALWAYS AS (price * (1 + tax_rate)) STORED,
    sku text NOT NULL UNIQUE
);
""")

    # File with dollar-quoted and escaped comments
    comments_sql = os.path.join(sql_dir, "comments.sql")
    with open(comments_sql, "w", encoding="utf-8") as f:
        f.write("""\
CREATE TABLE items (
    id serial PRIMARY KEY,
    name text NOT NULL
);

COMMENT ON TABLE items IS $$Items in the user's inventory$$;
COMMENT ON COLUMN items.name IS $desc$Item display name (can't be empty)$desc$;
""")

    return tmp_path


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


class TestDetection:
    def test_sql_never_auto_detected(self, tmp_path):
        ext = SqlExtractor()
        assert ext.detect(str(tmp_path)) is False

    def test_sql_not_detected_even_with_sql_files(self, tmp_path):
        (tmp_path / "schema.sql").touch()
        ext = SqlExtractor()
        assert ext.detect(str(tmp_path)) is False

    def test_name_is_sql(self):
        ext = SqlExtractor()
        assert ext.name == "sql"


# ---------------------------------------------------------------------------
# File extensions
# ---------------------------------------------------------------------------


class TestFileExtensions:
    def test_file_extensions(self):
        ext = SqlExtractor()
        assert ext.file_extensions() == [".sql"]


# ---------------------------------------------------------------------------
# Public symbols
# ---------------------------------------------------------------------------


class TestPublicSymbols:
    def test_create_table(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE TABLE users (\n"
            "    id serial PRIMARY KEY\n"
            ");\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["users"]

    def test_create_view(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE VIEW active_users AS SELECT * FROM users WHERE active;\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["active_users"]

    def test_create_type(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE TYPE status AS ENUM ('a', 'b');\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["status"]

    def test_create_function(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE FUNCTION do_thing() RETURNS void AS $$ BEGIN END; $$ LANGUAGE plpgsql;\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["do_thing"]

    def test_or_replace(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE OR REPLACE FUNCTION update_ts() RETURNS trigger AS $$ BEGIN END; $$;\n"
            "CREATE OR REPLACE VIEW v AS SELECT 1;\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert "update_ts" in symbols
        assert "v" in symbols

    def test_if_not_exists(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE TABLE IF NOT EXISTS events (\n"
            "    id serial PRIMARY KEY\n"
            ");\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["events"]

    def test_schema_qualified(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE TABLE public.users (id serial);\n"
            "CREATE TABLE audit.events (id serial);\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert "users" in symbols
        assert "events" in symbols

    def test_multiple_objects(self, sql_project):
        ext = SqlExtractor()
        symbols = ext.public_symbols(
            os.path.join(sql_project, "sql", "schema.sql")
        )
        assert "users" in symbols
        assert "posts" in symbols
        assert "active_users" in symbols
        assert "recent_posts" in symbols
        assert "status_type" in symbols
        assert "address" in symbols
        assert "update_timestamp" in symbols
        assert "soft_delete" in symbols

    def test_skips_comments(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "-- CREATE TABLE fake_table (id serial);\n"
            "/* CREATE TABLE other_fake (id serial); */\n"
            "CREATE TABLE real_table (id serial);\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert symbols == ["real_table"]

    def test_no_duplicates(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "CREATE TABLE t (id serial);\n"
            "CREATE OR REPLACE FUNCTION t() RETURNS void AS $$ BEGIN END; $$;\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        # "t" appears once even though it appears in both TABLE and FUNCTION
        assert symbols.count("t") == 1

    def test_case_insensitive(self, tmp_path):
        sql_file = tmp_path / "test.sql"
        sql_file.write_text(
            "create table lower_case (id serial);\n"
            "CREATE TABLE upper_case (id serial);\n"
            "Create Table mixed_case (id serial);\n",
            encoding="utf-8",
        )
        symbols = SqlExtractor().public_symbols(str(sql_file))
        assert "lower_case" in symbols
        assert "upper_case" in symbols
        assert "mixed_case" in symbols


# ---------------------------------------------------------------------------
# Table parsing
# ---------------------------------------------------------------------------


class TestParseCreateTable:
    def test_basic_columns(self):
        source = """\
CREATE TABLE users (
    id uuid NOT NULL,
    name text,
    age integer NOT NULL DEFAULT 0
);
"""
        tables = _parse_create_table(source)
        assert len(tables) == 1
        t = tables[0]
        assert t["name"] == "users"
        assert t["schema"] == ""
        assert len(t["columns"]) == 3

        id_col = t["columns"][0]
        assert id_col["name"] == "id"
        assert id_col["type"] == "uuid"
        assert id_col["nullable"] is False

        name_col = t["columns"][1]
        assert name_col["name"] == "name"
        assert name_col["type"] == "text"
        assert name_col["nullable"] is True

        age_col = t["columns"][2]
        assert age_col["name"] == "age"
        assert age_col["type"] == "integer"
        assert age_col["nullable"] is False
        assert age_col["default"] == "0"

    def test_types_int_text_timestamptz_uuid(self):
        source = """\
CREATE TABLE t (
    a integer,
    b text,
    c timestamptz,
    d uuid
);
"""
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["type"] == "integer"
        assert cols[1]["type"] == "text"
        assert cols[2]["type"] == "timestamptz"
        assert cols[3]["type"] == "uuid"

    def test_array_type(self):
        source = "CREATE TABLE t (tags text[], ids integer[]);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["type"] == "text[]"
        assert cols[1]["type"] == "integer[]"

    def test_custom_type(self):
        source = "CREATE TABLE t (status status_type NOT NULL);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["type"] == "status_type"

    def test_parameterized_type(self):
        source = "CREATE TABLE t (score numeric(10,2), label varchar(255));\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["type"] == "numeric(10,2)"
        assert cols[1]["type"] == "varchar(255)"

    def test_not_null(self):
        source = "CREATE TABLE t (a text NOT NULL, b text);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["nullable"] is False
        assert cols[1]["nullable"] is True

    def test_default_value(self):
        source = """\
CREATE TABLE t (
    a text NOT NULL DEFAULT 'hello',
    b integer DEFAULT 42,
    c boolean NOT NULL DEFAULT true,
    d timestamptz DEFAULT now()
);
"""
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert cols[0]["default"] == "'hello'"
        assert cols[1]["default"] == "42"
        assert cols[2]["default"] == "true"
        assert cols[3]["default"] == "now()"

    def test_generated_always_as_identity(self):
        source = "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert "GENERATED ALWAYS AS IDENTITY" in cols[0]["default"]

    def test_generated_by_default_as_identity(self):
        source = "CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert "GENERATED BY DEFAULT AS IDENTITY" in cols[0]["default"]

    def test_generated_stored(self):
        source = """\
CREATE TABLE t (
    price numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total numeric(10,2) GENERATED ALWAYS AS (price + tax) STORED
);
"""
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        total_col = cols[2]
        assert "GENERATED ALWAYS AS" in total_col["default"]
        assert "STORED" in total_col["default"]

    def test_inline_primary_key(self):
        source = "CREATE TABLE t (id serial PRIMARY KEY, name text);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert "PRIMARY KEY" in cols[0]["constraints"]

    def test_inline_unique(self):
        source = "CREATE TABLE t (email text UNIQUE);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert "UNIQUE" in cols[0]["constraints"]

    def test_inline_references(self):
        source = "CREATE TABLE t (user_id uuid REFERENCES users(id));\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        ref = [c for c in cols[0]["constraints"] if c.startswith("REFERENCES")]
        assert len(ref) == 1
        assert "users(id)" in ref[0]

    def test_table_level_constraints_skipped(self):
        source = """\
CREATE TABLE t (
    id serial,
    name text,
    PRIMARY KEY (id),
    UNIQUE (name),
    CHECK (length(name) > 0)
);
"""
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        # Only id and name should be columns, not the constraints
        assert len(cols) == 2
        assert cols[0]["name"] == "id"
        assert cols[1]["name"] == "name"

    def test_schema_qualified_table(self):
        source = "CREATE TABLE public.users (id serial);\n"
        tables = _parse_create_table(source)
        assert tables[0]["name"] == "users"
        assert tables[0]["schema"] == "public"

    def test_if_not_exists(self):
        source = "CREATE TABLE IF NOT EXISTS events (id serial);\n"
        tables = _parse_create_table(source)
        assert tables[0]["name"] == "events"

    def test_default_with_type_cast(self):
        source = "CREATE TABLE t (data jsonb NOT NULL DEFAULT '{}'::jsonb);\n"
        tables = _parse_create_table(source)
        cols = tables[0]["columns"]
        assert "::jsonb" in cols[0]["default"]


# ---------------------------------------------------------------------------
# View parsing
# ---------------------------------------------------------------------------


class TestParseCreateView:
    def test_basic_view(self):
        source = "CREATE VIEW v AS SELECT 1;\n"
        views = _parse_create_view(source)
        assert len(views) == 1
        assert views[0]["name"] == "v"
        assert views[0]["schema"] == ""

    def test_or_replace_view(self):
        source = "CREATE OR REPLACE VIEW v AS SELECT 1;\n"
        views = _parse_create_view(source)
        assert len(views) == 1
        assert views[0]["name"] == "v"

    def test_schema_qualified_view(self):
        source = "CREATE VIEW public.v AS SELECT 1;\n"
        views = _parse_create_view(source)
        assert views[0]["name"] == "v"
        assert views[0]["schema"] == "public"


# ---------------------------------------------------------------------------
# Type parsing
# ---------------------------------------------------------------------------


class TestParseCreateType:
    def test_enum_type(self):
        source = "CREATE TYPE status AS ENUM ('draft', 'published', 'archived');\n"
        types = _parse_create_type(source)
        assert len(types) == 1
        t = types[0]
        assert t["name"] == "status"
        assert t["kind"] == "enum"
        assert t["values"] == ["draft", "published", "archived"]
        assert t["fields"] == []

    def test_composite_type(self):
        source = """\
CREATE TYPE address AS (
    street text,
    city text,
    zip_code text
);
"""
        types = _parse_create_type(source)
        assert len(types) == 1
        t = types[0]
        assert t["name"] == "address"
        assert t["kind"] == "composite"
        assert t["values"] == []
        assert len(t["fields"]) == 3
        assert t["fields"][0] == {"name": "street", "type": "text"}
        assert t["fields"][1] == {"name": "city", "type": "text"}
        assert t["fields"][2] == {"name": "zip_code", "type": "text"}

    def test_enum_with_escaped_quotes(self):
        source = "CREATE TYPE label AS ENUM ('it''s', 'they''re');\n"
        types = _parse_create_type(source)
        assert types[0]["values"] == ["it's", "they're"]

    def test_schema_qualified_type(self):
        source = "CREATE TYPE public.status AS ENUM ('a', 'b');\n"
        types = _parse_create_type(source)
        assert types[0]["name"] == "status"
        assert types[0]["schema"] == "public"


# ---------------------------------------------------------------------------
# Function parsing
# ---------------------------------------------------------------------------


class TestParseCreateFunction:
    def test_basic_function(self):
        source = """\
CREATE FUNCTION do_thing(x integer) RETURNS void AS $$
BEGIN
END;
$$ LANGUAGE plpgsql;
"""
        functions = _parse_create_function(source)
        assert len(functions) == 1
        assert functions[0]["name"] == "do_thing"

    def test_or_replace_function(self):
        source = """\
CREATE OR REPLACE FUNCTION update_ts() RETURNS trigger AS $$
BEGIN END;
$$ LANGUAGE plpgsql;
"""
        functions = _parse_create_function(source)
        assert len(functions) == 1
        assert functions[0]["name"] == "update_ts"

    def test_schema_qualified_function(self):
        source = "CREATE FUNCTION public.my_func() RETURNS void AS $$ BEGIN END; $$;\n"
        functions = _parse_create_function(source)
        assert functions[0]["name"] == "my_func"
        assert functions[0]["schema"] == "public"

    def test_no_duplicate_functions(self):
        source = """\
CREATE OR REPLACE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;
CREATE OR REPLACE FUNCTION f() RETURNS void AS $$ BEGIN END; $$;
"""
        functions = _parse_create_function(source)
        assert len(functions) == 1


# ---------------------------------------------------------------------------
# COMMENT ON parsing
# ---------------------------------------------------------------------------


class TestParseComments:
    def test_table_comment(self):
        source = "COMMENT ON TABLE users IS 'Registered user accounts';\n"
        comments = _parse_comments(source)
        assert comments[("table", "users")] == "Registered user accounts"

    def test_column_comment(self):
        source = "COMMENT ON COLUMN users.email IS 'User email address';\n"
        comments = _parse_comments(source)
        assert comments[("column", "users.email")] == "User email address"

    def test_escaped_single_quotes(self):
        source = "COMMENT ON TABLE items IS 'Items in the user''s inventory';\n"
        comments = _parse_comments(source)
        assert comments[("table", "items")] == "Items in the user's inventory"

    def test_dollar_quoting_empty_tag(self):
        source = "COMMENT ON TABLE items IS $$Dollar quoted text$$;\n"
        comments = _parse_comments(source)
        assert comments[("table", "items")] == "Dollar quoted text"

    def test_dollar_quoting_named_tag(self):
        source = "COMMENT ON TABLE items IS $desc$Tagged dollar quote$desc$;\n"
        comments = _parse_comments(source)
        assert comments[("table", "items")] == "Tagged dollar quote"

    def test_is_null_removes_comment(self):
        source = """\
COMMENT ON TABLE users IS 'Some text';
COMMENT ON TABLE users IS NULL;
"""
        comments = _parse_comments(source)
        # IS NULL should not add the comment (only the first one exists,
        # or IS NULL should override -- in our implementation IS NULL is skipped,
        # so the first one remains)
        # The important thing: IS NULL does not crash or produce garbage
        assert ("table", "users") in comments

    def test_schema_qualified_comment(self):
        source = "COMMENT ON TABLE public.sessions IS 'Active sessions';\n"
        comments = _parse_comments(source)
        assert comments[("table", "public.sessions")] == "Active sessions"

    def test_schema_qualified_column_comment(self):
        source = "COMMENT ON COLUMN public.sessions.token IS 'Auth token';\n"
        comments = _parse_comments(source)
        assert comments[("column", "public.sessions.token")] == "Auth token"

    def test_view_comment(self):
        source = "COMMENT ON VIEW active_users IS 'Only active users';\n"
        comments = _parse_comments(source)
        assert comments[("view", "active_users")] == "Only active users"

    def test_function_comment(self):
        source = "COMMENT ON FUNCTION update_ts IS 'Timestamp trigger';\n"
        comments = _parse_comments(source)
        assert comments[("function", "update_ts")] == "Timestamp trigger"

    def test_multiline_comment_string(self):
        source = """\
COMMENT ON TABLE users IS 'This is a
multiline comment
spanning three lines';
"""
        comments = _parse_comments(source)
        assert "multiline comment" in comments[("table", "users")]
        assert "spanning three lines" in comments[("table", "users")]

    def test_case_insensitive_keywords(self):
        source = "comment on table users is 'lower case keywords';\n"
        comments = _parse_comments(source)
        assert comments[("table", "users")] == "lower case keywords"


# ---------------------------------------------------------------------------
# ref handler
# ---------------------------------------------------------------------------


class TestRefHandler:
    def test_ref_groups_by_type(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "### Tables" in result
        assert "### Views" in result
        assert "### Types" in result
        assert "### Functions" in result

    def test_ref_lists_tables_with_comments(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "**users**" in result
        assert "Registered user accounts" in result
        assert "**posts**" in result
        assert "User-created blog posts" in result

    def test_ref_lists_views(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "**active_users**" in result
        assert "**recent_posts**" in result

    def test_ref_lists_enum_type_with_values(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "**status_type**" in result
        assert "ENUM:" in result
        assert "draft" in result
        assert "published" in result
        assert "archived" in result

    def test_ref_lists_composite_type(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "**address**" in result
        assert "COMPOSITE:" in result
        assert "street text" in result

    def test_ref_lists_functions(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "**update_timestamp**" in result
        assert "**soft_delete**" in result
        assert "Auto-update timestamp trigger function" in result

    def test_ref_no_arg_errors(self):
        ext = SqlExtractor()
        result = ext.extract("ref", {"path": ""}, [], [], "/tmp")
        assert "selfdoc:" in result
        assert "requires" in result

    def test_ref_file_not_found_errors(self, tmp_path):
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "nonexistent.sql"},
            [],
            [],
            str(tmp_path),
        )
        assert "selfdoc:" in result
        assert "not found" in result

    def test_ref_no_objects_errors(self, tmp_path):
        sql_file = tmp_path / "empty.sql"
        sql_file.write_text("-- just a comment\n", encoding="utf-8")
        ext = SqlExtractor()
        result = ext.extract(
            "ref",
            {"path": "empty.sql"},
            [],
            [],
            str(tmp_path),
        )
        assert "selfdoc:" in result
        assert "no CREATE objects" in result


# ---------------------------------------------------------------------------
# prose-desc handler
# ---------------------------------------------------------------------------


class TestProseDescHandler:
    def test_prose_desc_returns_table_comment(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "prose-desc",
            {"path": "sql/schema.sql", "target": "users"},
            [],
            [],
            str(sql_project),
        )
        assert result == "Registered user accounts"

    def test_prose_desc_no_target_errors(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "prose-desc",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        assert "selfdoc:" in result
        assert "requires a target" in result

    def test_prose_desc_table_not_found(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "prose-desc",
            {"path": "sql/schema.sql", "target": "nonexistent"},
            [],
            [],
            str(sql_project),
        )
        assert "selfdoc:" in result
        assert "no comment found" in result

    def test_prose_desc_no_arg_errors(self):
        ext = SqlExtractor()
        result = ext.extract("prose-desc", {"path": ""}, [], [], "/tmp")
        assert "selfdoc:" in result
        assert "requires" in result


# ---------------------------------------------------------------------------
# table-schema handler
# ---------------------------------------------------------------------------


class TestTableSchemaHandler:
    def test_table_schema_basic(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "users"},
            [],
            [],
            str(sql_project),
        )
        assert "| Column | Type | Nullable | Default | Description |" in result
        assert "`id`" in result
        assert "`uuid`" in result
        assert "NOT NULL" in result
        assert "`email`" in result
        assert "User email address" in result

    def test_table_schema_with_column_comments(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "users"},
            [],
            [],
            str(sql_project),
        )
        assert "Unique user identifier" in result
        assert "User email address, must be unique" in result
        assert "Optional display name" in result

    def test_table_schema_single_table_no_target(self, tmp_path):
        sql_file = tmp_path / "single.sql"
        sql_file.write_text(
            "CREATE TABLE only_one (id serial, name text NOT NULL);\n",
            encoding="utf-8",
        )
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "single.sql"},
            [],
            [],
            str(tmp_path),
        )
        assert "`id`" in result
        assert "`name`" in result

    def test_table_schema_multiple_tables_no_target(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql"},
            [],
            [],
            str(sql_project),
        )
        # Both table names should appear as headings
        assert "### users" in result
        assert "### posts" in result

    def test_table_schema_table_not_found(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "nonexistent"},
            [],
            [],
            str(sql_project),
        )
        assert "selfdoc:" in result
        assert "not found" in result

    def test_table_schema_no_tables(self, tmp_path):
        sql_file = tmp_path / "views_only.sql"
        sql_file.write_text(
            "CREATE VIEW v AS SELECT 1;\n",
            encoding="utf-8",
        )
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "views_only.sql"},
            [],
            [],
            str(tmp_path),
        )
        assert "selfdoc:" in result
        assert "no tables" in result

    def test_table_schema_generated_identity(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "posts"},
            [],
            [],
            str(sql_project),
        )
        assert "GENERATED ALWAYS AS IDENTITY" in result

    def test_table_schema_generated_stored(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/generated.sql", "target": "products"},
            [],
            [],
            str(sql_project),
        )
        assert "GENERATED ALWAYS AS" in result
        assert "STORED" in result

    def test_table_schema_references(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "posts"},
            [],
            [],
            str(sql_project),
        )
        assert "Reference to the post author" in result

    def test_table_schema_array_type(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/schema.sql", "target": "posts"},
            [],
            [],
            str(sql_project),
        )
        assert "`text[]`" in result

    def test_table_schema_dollar_quoted_comments(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/comments.sql", "target": "items"},
            [],
            [],
            str(sql_project),
        )
        # Column comment from dollar-quoting should be applied
        assert "Item display name" in result

    def test_table_schema_no_arg_errors(self):
        ext = SqlExtractor()
        result = ext.extract("table-schema", {"path": ""}, [], [], "/tmp")
        assert "selfdoc:" in result
        assert "requires" in result

    def test_table_schema_json_delegation(self, tmp_path):
        """JSON files should delegate to handle_table_config."""
        json_file = tmp_path / "config.json"
        json_file.write_text('{"key": "value"}', encoding="utf-8")
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "config.json"},
            [],
            [],
            str(tmp_path),
        )
        assert "`key`" in result
        assert "string" in result

    def test_table_schema_schema_qualified(self, sql_project):
        ext = SqlExtractor()
        result = ext.extract(
            "table-schema",
            {"path": "sql/qualified.sql", "target": "sessions"},
            [],
            [],
            str(sql_project),
        )
        assert "`id`" in result
        assert "`user_id`" in result
        assert "`token`" in result
        # Column comment from schema-qualified COMMENT ON
        assert "Session authentication token" in result


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


class TestResolvePath:
    def test_resolve_sql_file(self, sql_project):
        ext = SqlExtractor()
        result = ext.resolve_path("sql/schema.sql", [], str(sql_project))
        assert result is not None
        assert result.endswith("schema.sql")

    def test_resolve_sql_directory(self, sql_project):
        ext = SqlExtractor()
        result = ext.resolve_path("sql", [], str(sql_project))
        assert result is not None
        assert result.endswith("sql")

    def test_resolve_sql_with_source_paths(self, sql_project):
        ext = SqlExtractor()
        result = ext.resolve_path("schema.sql", ["sql/"], str(sql_project))
        assert result is not None
        assert result.endswith("schema.sql")

    def test_resolve_sql_implicit_extension(self, sql_project):
        ext = SqlExtractor()
        result = ext.resolve_path("sql/schema", [], str(sql_project))
        assert result is not None
        assert result.endswith("schema.sql")

    def test_resolve_sql_not_found(self, sql_project):
        ext = SqlExtractor()
        result = ext.resolve_path("nonexistent.sql", [], str(sql_project))
        assert result is None


# ---------------------------------------------------------------------------
# Unknown directive
# ---------------------------------------------------------------------------


class TestUnknownDirective:
    def test_unknown_directive_errors(self):
        ext = SqlExtractor()
        result = ext.extract(
            "code-test",
            {"path": "test.sql"},
            [],
            [],
            "/tmp",
        )
        assert "selfdoc:" in result
        assert "unknown directive" in result


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


class TestRegistration:
    def test_sql_in_extractors(self):
        from selfdoc.extractors import EXTRACTORS
        assert "sql" in EXTRACTORS
        assert isinstance(EXTRACTORS["sql"], SqlExtractor)

    def test_sql_not_in_detection_order(self):
        from selfdoc.extractors import _DETECTION_ORDER
        for ext in _DETECTION_ORDER:
            assert ext.name != "sql"


# ---------------------------------------------------------------------------
# symbol_details
# ---------------------------------------------------------------------------


class TestSymbolDetails:
    def test_symbol_details_function(self, tmp_path):
        sql_file = tmp_path / "funcs.sql"
        sql_file.write_text(
            "CREATE OR REPLACE FUNCTION calculate_total(\n"
            "    user_id INTEGER,\n"
            "    IN amount NUMERIC,\n"
            "    discount NUMERIC DEFAULT 0\n"
            ") RETURNS NUMERIC\n"
            "LANGUAGE plpgsql\n"
            "AS $$\n"
            "BEGIN\n"
            "    RETURN amount - discount;\n"
            "END;\n"
            "$$;\n"
            "\n"
            "COMMENT ON FUNCTION calculate_total IS "
            "'Calculate the total after discount.';\n",
            encoding="utf-8",
        )
        ext = SqlExtractor()
        details = ext.symbol_details(str(sql_file), "calculate_total")
        assert details is not None

        params = details["params"]
        assert len(params) == 3

        assert params[0]["name"] == "user_id"
        assert params[0]["type"] == "INTEGER"
        assert params[0]["documented"] is False

        assert params[1]["name"] == "amount"
        assert params[1]["type"] == "NUMERIC"
        assert params[1]["documented"] is False

        assert params[2]["name"] == "discount"
        assert params[2]["type"] == "NUMERIC"
        assert params[2]["documented"] is False

        assert details["return_type"] == "NUMERIC"
        assert details["return_documented"] is True

    def test_symbol_details_table_returns_none(self, tmp_path):
        sql_file = tmp_path / "tables.sql"
        sql_file.write_text(
            "CREATE TABLE users (\n"
            "    id SERIAL PRIMARY KEY,\n"
            "    name TEXT NOT NULL\n"
            ");\n",
            encoding="utf-8",
        )
        ext = SqlExtractor()
        details = ext.symbol_details(str(sql_file), "users")
        assert details is None

    def test_symbol_details_unknown_returns_none(self, tmp_path):
        sql_file = tmp_path / "any.sql"
        sql_file.write_text(
            "CREATE TABLE t (id serial);\n",
            encoding="utf-8",
        )
        ext = SqlExtractor()
        details = ext.symbol_details(str(sql_file), "nonexistent")
        assert details is None
