"""The spelling engine: one word checker serving every surface that needs one.

``selfdoc check`` runs it over a project's docs and posts (SPELL001), and
``selfdoc spell-corpus`` runs the same engine over every sibling project on
the machine.  There is one engine and one accept list; a surface that wants
spelling asks this module, and no surface carries a second opinion about
what a word is.

Vendored word list and its licence obligations
----------------------------------------------

The acceptance oracle is a pinned snapshot of the **English Speller Database**
(ESDB, formerly SCOWL), generated from https://app.aspell.net/create at size
70 with US, British (-ise and -ize) and Canadian spellings.  It ships as
package data in ``selfdoc_core/wordlist/``:

- ``words.txt`` -- the words.
- ``COPYRIGHT.txt`` -- upstream's copyright file, verbatim.
- ``SOURCE.json`` -- the retrieval record (URL, every parameter, upstream git
  revisions, SHA-256, word count), regenerated by
  ``scripts/regen_wordlist.py``.

Upstream's grant permits use, copying, modification, distribution and sale of
word lists created from the database "provided that the above copyright
notice appears in all copies and that both the above copyright notice and
this notice appear in supporting documentation".  Shipping ``COPYRIGHT.txt``
verbatim beside the words is what satisfies that, and it carries the
sub-source notices upstream attaches -- the UK Advanced Cryptics Dictionary
notice in particular, whose own terms require that it "be prominently
displayed and the text of this document must be included verbatim".  Never
ship ``words.txt`` without ``COPYRIGHT.txt``; never edit either by hand.

Two candidates were rejected before this one.  A widely-used word-frequency
corpus carries a share-alike condition on its data, which would reach the
package that redistributes it.  The largest public-domain English list is an
unfiltered scrape: it accepts enough garbage to be worthless as an
acceptance oracle, which is the one job here.

The accept list
---------------

Genuine terms the general English list cannot know -- project names, tool
names, technical vocabulary -- live in a single plain-text file at
:data:`ACCEPT_LIST_PATH` (``~/Projects/ark/spelling-accept.txt``).  One word
per line, ``#`` starts a comment, and a word on the list is accepted
everywhere, permanently.

That location is outside every repository, so the list has no version
history and no backup.  This was chosen deliberately: the list is
cross-project by nature and belongs to the machine rather than to any one
repo, and losing it costs a re-triage, not correctness.

**A missing file means an empty list, not an error.**  A fresh machine has
simply never accepted anything yet; that is genuine absence, not a degraded
mode, and the check behaves identically before and after the file appears --
it just has fewer accepted terms.  A file that *exists* and is malformed is
a hard error: it was written by someone who meant something by it, and
guessing at their intent would silently drop accepted terms.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from importlib.resources import files
from pathlib import Path

from selfdoc_core.directives import blank_backtick_spans
from selfdoc_core.tokenizer import TEXT_BEARING, tokenize

# The one accept list, shared by every project on the machine.
ACCEPT_LIST_PATH = Path.home() / "Projects" / "ark" / "spelling-accept.txt"

_WORDLIST_DIR = "wordlist"


class AcceptListError(RuntimeError):
    """Raised when the accept list exists but cannot be read as written.

    Never raised for a missing file -- absence is an empty list.  Raised for
    a line the format does not admit, naming the file, the line number and
    what was wrong with it.
    """


@dataclass(frozen=True, slots=True)
class Misspelling:
    """One unrecognized word, located precisely enough to open and fix."""

    file: str
    line: int          # 1-based
    column: int        # 1-based, in the raw source line
    word: str
    suggestions: tuple[str, ...] = ()

    def describe(self) -> str:
        """Render the diagnostic message a lint carries."""
        text = f"Unrecognized word '{self.word}' (col {self.column})"
        if self.suggestions:
            text += f"; did you mean {', '.join(self.suggestions)}?"
        return text


# -- The vocabulary -----------------------------------------------------------


@lru_cache(maxsize=1)
def load_wordlist() -> frozenset[str]:
    """Load the vendored ESDB word list, exactly as vendored."""
    raw = files("selfdoc_core").joinpath(_WORDLIST_DIR, "words.txt").read_text(
        encoding="utf-8",
    )
    return frozenset(line for line in raw.split("\n") if line)


@lru_cache(maxsize=1)
def wordlist_source() -> dict:
    """Return the vendored word list's retrieval record."""
    raw = files("selfdoc_core").joinpath(_WORDLIST_DIR, "SOURCE.json").read_text(
        encoding="utf-8",
    )
    return json.loads(raw)


@lru_cache(maxsize=1)
def wordlist_copyright() -> str:
    """Return upstream's copyright notice, verbatim, for display."""
    return files("selfdoc_core").joinpath(
        _WORDLIST_DIR, "COPYRIGHT.txt",
    ).read_text(encoding="utf-8")


# An accept-list entry is a single word: letters, with apostrophes allowed
# inside contractions and possessives.  Nothing else, because nothing else
# could ever be consulted -- the checker splits hyphenated compounds into
# their parts and skips any token carrying a digit, so a hyphenated or
# numeric entry would sit on the list accepting nothing.
_ACCEPT_ENTRY_RE = re.compile(r"^[^\W\d_]+(?:['’][^\W\d_]+)*$")


def load_accept_list(path: Path | str | None = None) -> frozenset[str]:
    """Read the accept list at *path* (default :data:`ACCEPT_LIST_PATH`).

    Returns:
        Every accepted word, empty when the file does not exist.

    Raises:
        AcceptListError: When the file exists and any line is not a bare
            word, naming the line number and the reason.
    """
    target = Path(path) if path is not None else ACCEPT_LIST_PATH
    if not target.is_file():
        return frozenset()

    accepted: set[str] = set()
    text = target.read_text(encoding="utf-8")
    for lineno, raw in enumerate(text.split("\n"), start=1):
        entry = raw.split("#", 1)[0].strip()
        if not entry:
            continue
        if not _ACCEPT_ENTRY_RE.match(entry):
            raise AcceptListError(
                f"{target}:{lineno}: {entry!r} is not a single word. An "
                f"accept-list line holds one word (letters, with "
                f"apostrophes allowed inside it) or a '#' comment. Split a "
                f"hyphenated compound into its parts and give each its own "
                f"line -- the checker checks the parts, so a hyphenated "
                f"entry would accept nothing."
            )
        accepted.add(entry)
    return frozenset(accepted)


# -- Word scanning ------------------------------------------------------------

# Markdown and HTML constructs whose content is never prose.  Each is blanked
# with same-length spaces so every surviving character keeps its column.
_MASKS = (
    # Link and image destinations: the text stays, the URL goes.
    re.compile(r"\]\([^)\n]*\)"),
    # Reference-style link labels and link-reference definitions.
    re.compile(r"\]\[[^\]\n]*\]"),
    re.compile(r"^\s*\[[^\]\n]+\]:\s*\S+", re.MULTILINE),
    # HTML tags, comments and autolinks.  A tag's attributes are inside it,
    # so the pattern has to admit whitespace -- the earlier form stopped at
    # the first space and let the element name and every attribute value
    # through as prose.  The opening character still has to look like the
    # start of a tag (a name, a closing slash, or a `!` declaration), which
    # keeps a comparison written in prose ("x < y and z > 0") out of it.  A
    # tag broken across lines is not covered: the scanner is handed one raw
    # source line at a time, so the columns it reports stay true.
    re.compile(r"</?[A-Za-z!][^<>]*>"),
    # Bare URLs and mail addresses left loose in prose.
    re.compile(r"\b[a-z][a-z0-9+.-]*://\S+"),
    re.compile(r"\bmailto:\S+"),
    # Directive markers.  The block forms are their own tokens, but the
    # inline ':-:' marker and its attributes live inside a paragraph.
    re.compile(r":-:\s+[\w-]+(?:\s+[\w-]+=\"[^\"\n]*\")*"),
    re.compile(r"^(?::-:|:<:|:@:|:=:|:::|:>:)(?=\s|$)", re.MULTILINE),
)

# A whitespace-delimited chunk holding any of these is a machine token --
# an identifier, a path, a version, a qualified name -- not English.  The
# whole chunk is skipped rather than picked apart, because the letters in
# ``os.path`` and ``max_size`` are not words anyone can misspell.
_MACHINE_CHUNK_RE = re.compile(
    r"[0-9_/\\@~^$*]"          # digits and the punctuation identifiers use
    r"|::"                      # namespace separators
    r"|[^\W\d_]\.[^\W\d_]"      # a dot joining two letters: os.path, e.g.
)

# A word: letters, with apostrophes allowed inside and one allowed at the
# end (a plural possessive).  Hyphens are separators, not part of a word, so
# a hyphenated compound arrives here already split into its parts.
_WORD_RE = re.compile(r"[^\W\d_]+(?:['’][^\W\d_]+)*['’]?")

# An internal case change marks camelCase or PascalCase: an identifier
# spelled into prose without backticks.  Skipped, because the alternative is
# flagging every unbackticked symbol name in the fleet's documentation.
#
# Two shapes, because a case change has two directions.  A capital after a
# lowercase letter is the familiar one (``parseFrontmatter``,
# ``TextResponse``).  The other is a run of capitals ending against a
# capitalized word -- ``JSONResponse``, ``XMLHttpRequest``, ``IOError`` --
# where the acronym and the word meet capital-to-capital and there is no
# lowercase letter before the boundary at all.  Requiring two capitals in
# the run keeps an ordinary capitalized word out: ``Adress`` starting a
# sentence is still a misspelling to report.
_INNER_CAPITAL_RE = re.compile(r"[a-z][A-Z]|[A-Z]{2}[a-z]")

_ALPHABET = "abcdefghijklmnopqrstuvwxyz"


def _blank(line: str) -> str:
    """Blank every non-prose construct in *line*, preserving its columns."""
    masked = blank_backtick_spans(line)
    for pattern in _MASKS:
        masked = pattern.sub(lambda m: " " * len(m.group(0)), masked)
    return masked


def _is_known(word: str, vocab: frozenset[str]) -> bool:
    """True when *vocab* holds *word* in a standard casing form.

    Exact first, so an acronym the list carries ("USA", "CPU") is accepted
    as written.  Then lowercase, so a capitalized sentence start and an
    all-caps heading are accepted from the ordinary entry.
    """
    return word in vocab or word.lower() in vocab


def _accepts(word: str, vocab: frozenset[str]) -> bool:
    """True when *word* is spelled acceptably against *vocab*."""
    if len(word) < 2:
        # A lone letter is an enumeration marker or an initial, never a
        # misspelling anyone can act on.
        return True
    if _INNER_CAPITAL_RE.search(word):
        return True
    if _is_known(word, vocab):
        return True
    # Possessives: the list carries "dog's" but not every proper noun's.
    for suffix in ("'s", "’s", "'", "’"):
        if word.endswith(suffix):
            base = word[: -len(suffix)]
            if base and _is_known(base, vocab):
                return True
    return False


def suggestions_for(word: str, vocab: frozenset[str], limit: int = 3) -> tuple[str, ...]:
    """Return up to *limit* edit-distance-1 neighbours of *word* in *vocab*.

    Deliberately cheap: one edit, generated and looked up, no scoring model
    and no distance-2 search.  A word with no neighbour gets no suggestion,
    which is a better answer than an expensive wrong one.
    """
    lowered = word.lower()
    if len(lowered) > 16:
        return ()
    splits = [(lowered[:i], lowered[i:]) for i in range(len(lowered) + 1)]
    candidates: set[str] = set()
    for left, right in splits:
        if right:
            candidates.add(left + right[1:])                       # delete
            if len(right) > 1:
                candidates.add(left + right[1] + right[0] + right[2:])  # swap
            for letter in _ALPHABET:
                candidates.add(left + letter + right[1:])          # replace
        for letter in _ALPHABET:
            candidates.add(left + letter + right)                  # insert
    candidates.discard(lowered)
    hits = sorted(c for c in candidates if c in vocab)
    return tuple(hits[:limit])


def iter_unknown_words(
    line: str,
    vocab: frozenset[str],
) -> list[tuple[int, str]]:
    """Return ``(column, word)`` for every unrecognized word in one source line.

    *line* is a raw source line, so the returned columns are 0-based offsets
    into it.  Markers, code spans, URLs and directive syntax are blanked
    before scanning, and machine tokens are skipped whole.
    """
    masked = _blank(line)
    found: list[tuple[int, str]] = []
    for chunk_match in re.finditer(r"\S+", masked):
        chunk = chunk_match.group(0)
        if _MACHINE_CHUNK_RE.search(chunk):
            continue
        base = chunk_match.start()
        for word_match in _WORD_RE.finditer(chunk):
            word = word_match.group(0)
            if not _accepts(word, vocab):
                found.append((base + word_match.start(), word))
    return found


def check_text(
    content: str,
    *,
    file: str,
    vocab: frozenset[str] | None = None,
    accepted: frozenset[str] | None = None,
    line_offset: int = 0,
    suggest: bool = True,
) -> list[Misspelling]:
    """Spell-check Markdown *content*, reporting file, line and column.

    Structure comes from the block tokenizer: only text-bearing tokens are
    scanned, so fenced code blocks and directive blocks are excluded by
    construction rather than by pattern-matching them back out.  Within a
    token the RAW source lines are scanned, not the token's parsed text, so
    every reported column is a real column in the file.

    Args:
        content: Markdown body, frontmatter already removed.
        file: Path to name in each diagnostic.
        vocab: Word list to accept against; the vendored list when None.
        accepted: The accept list; loaded from :data:`ACCEPT_LIST_PATH`
            when None.
        line_offset: Added to every reported line, for a body whose
            frontmatter was stripped.
        suggest: Whether to compute edit-distance-1 suggestions.

    Returns:
        One :class:`Misspelling` per unrecognized word, in document order.
    """
    words = load_wordlist() if vocab is None else vocab
    accept = load_accept_list() if accepted is None else accepted
    known = words | accept if accept else words

    lines = content.split("\n")
    results: list[Misspelling] = []
    for tok in tokenize(content):
        if not isinstance(tok, TEXT_BEARING):
            continue
        for lineno in range(tok.start, tok.end + 1):
            if lineno < 1 or lineno > len(lines):
                continue
            raw = lines[lineno - 1]
            for column, word in iter_unknown_words(raw, known):
                results.append(Misspelling(
                    file=file,
                    line=lineno + line_offset,
                    column=column + 1,
                    word=word,
                    suggestions=(
                        suggestions_for(word, known) if suggest else ()
                    ),
                ))
    return results
