package assembly

import (
	"sort"
	"strings"

	"github.com/smm-h/selfdoc/internal/blog/shared"
	"github.com/smm-h/selfdoc/internal/util"
)

// GenerateWorkerJS returns the Cloudflare Pages _worker.js for the assembly
// site.
//
// The worker does two things, and every request answers to at most one 301
// before it reaches an asset.
//
// # One hostname
//
// The site is bound to more than one host -- the canonical apex, the docs
// subdomain, the retired blog subdomain, the provider's own preview domain --
// and one of them serves content. A request on any other host is redirected to
// the same path on the canonical host, 301, query string preserved. No path is
// ever served on two hosts, so nothing is duplicate content and no
// rel=canonical is asked to undo a hosting decision.
//
// The one host that does not map to the same path is the retired blog
// subdomain, whose whole document space was the blog: "blog.example.com/x" is
// "<canonical>/blog/x", not "<canonical>/x". Mapping it to the same path would
// send every live post link to the site root, where nothing answers.
//
// # Historical addresses
//
// The site has changed address scheme twice, and the shapes below are the ones
// with links in the wild. Each is a 301 to the current address, generated as
// *data* from the manifests -- the assembly knows every project slug and every
// post slug, and a path that merely looks historical without naming one of
// them is not redirected at all: it falls through to the 404, which is the
// honest answer for an address that never existed.
//
//   - "/<slug>/<locale>/<version>/<rest>" -> "/<slug>/<rest>". The version
//     segment is not preserved: any version collapses to the stable address.
//     Archived versions are still served from "/<slug>/v/<version>/", but an
//     old deep link is far more likely to want the page as it is now than the
//     page as it was at the version that happened to be current when somebody
//     copied the URL.
//   - "/<slug>/posts/<post>/" -> "/blog/<post>/". Posts moved out of the
//     project subtrees into one site-level namespace.
//
// The third historical shape, the flat "/<slug>/<page>/" sitemap address,
// needs no rule: it is what the current scheme serves, and the meta-refresh
// stubs that briefly stood at "/<slug>/" have been replaced by the real pages
// at the same address.
//
// canonicalBase is the absolute base URL of the assembly site, taken from
// topology.docs_base. Required -- there is no default deploy target.
//
// legacyBlogHost is the hostname of the retired blog subdomain, taken from
// topology.legacy_blog_host. An empty string means no such subdomain exists
// and it gets no prefix entry; it would still be redirected by the
// one-hostname rule if it resolved here.
//
// projectSlugs is every project the assembly serves. A historical path is only
// rewritten when its first segment is one of these. postSlugs is every post
// the blog serves, same role.
func GenerateWorkerJS(
	canonicalBase string,
	legacyBlogHost string,
	projectSlugs []string,
	postSlugs []string,
) (string, error) {
	if canonicalBase == "" {
		return "", errorf(
			"GenerateWorkerJS requires a canonical base URL " +
				"(topology.docs_base); there is no default.",
		)
	}
	canonicalBase = strings.TrimRight(canonicalBase, "/")

	hostPrefixes := "[]"
	if legacyBlogHost != "" {
		hostPrefixes = "[[" +
			util.PythonJSONString(legacyBlogHost) + ", " +
			util.PythonJSONString("/"+shared.PostsSegment) + "]]"
	}

	var b strings.Builder
	b.WriteString("// Generated by selfdoc. Do not edit: regenerated on every deploy.\n")
	b.WriteString("const CANONICAL_BASE = " + util.PythonJSONString(canonicalBase) + ";\n")
	b.WriteString("const CANONICAL_HOST = new URL(CANONICAL_BASE).hostname;\n")
	b.WriteString("\n")
	b.WriteString("// Non-canonical hosts whose paths land under a prefix on the\n")
	b.WriteString("// canonical host. Every other non-canonical host maps to the same\n")
	b.WriteString("// path, so it needs no entry here. A Map, not an object: a hostname\n")
	b.WriteString("// is attacker-chosen input, and an object lookup would answer\n")
	b.WriteString("// 'constructor' and '__proto__' with something from the prototype.\n")
	b.WriteString("const HOST_PREFIXES = new Map(" + hostPrefixes + ");\n")
	b.WriteString("\n")
	b.WriteString("// The address space, as data. A historical-looking path that names\n")
	b.WriteString("// neither a real project nor a real post is not redirected.\n")
	b.WriteString("const PROJECT_SLUGS = new Set(" + jsStringArray(projectSlugs) + ");\n")
	b.WriteString("const POST_SLUGS = new Set(" + jsStringArray(postSlugs) + ");\n")
	b.WriteString("\n")
	b.WriteString("// /<slug>/<locale>/<version>/<rest> -- the retired locale+version scheme.\n")
	b.WriteString("const LOCALE_VERSION = ")
	b.WriteString("/^\\/([^/]+)\\/([a-z]{2}(?:-[a-z]{2})?)\\/([^/]+)(?:\\/(.*))?$/i;\n")
	b.WriteString("// What counts as a version segment: 1, 1.2, v1.2.3, 1.2.3-rc.1.\n")
	b.WriteString("const VERSION = /^v?\\d+(?:\\.\\d+)*(?:[-+][0-9A-Za-z.-]+)?$/;\n")
	b.WriteString("// /<slug>/posts/<post>/ -- posts before they became site-level.\n")
	b.WriteString("const PROJECT_POST = /^\\/([^/]+)\\/posts\\/([^/]+)\\/?$/;\n")
	b.WriteString("\n")
	b.WriteString("// One pass of the mapping: the path this address maps to, or null.\n")
	b.WriteString("function legacyStep(pathname) {\n")
	b.WriteString("  const post = pathname.match(PROJECT_POST);\n")
	b.WriteString("  if (post && PROJECT_SLUGS.has(post[1]) && POST_SLUGS.has(post[2])) {\n")
	b.WriteString("    return \"/" + shared.PostsSegment + "/\" + post[2] + \"/\";\n")
	b.WriteString("  }\n")
	b.WriteString("  const versioned = pathname.match(LOCALE_VERSION);\n")
	b.WriteString("  if (versioned && PROJECT_SLUGS.has(versioned[1]) &&\n")
	b.WriteString("      VERSION.test(versioned[3])) {\n")
	b.WriteString("    return \"/\" + versioned[1] + \"/\" + (versioned[4] || \"\");\n")
	b.WriteString("  }\n")
	b.WriteString("  return null;\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("// The path a historical address maps to, or null when it is not one.\n")
	b.WriteString("// The mapping is applied to its own output until it stops matching:\n")
	b.WriteString("// /<slug>/<locale>/<version>/<slug>/<locale>/<version>/x maps to an\n")
	b.WriteString("// address that is itself historical, and a redirect that lands on a\n")
	b.WriteString("// redirect is a chain. Every pass drops at least one path segment,\n")
	b.WriteString("// so the segment count bounds the number of passes and a path built\n")
	b.WriteString("// to loop terminates.\n")
	b.WriteString("export function legacyTarget(pathname) {\n")
	b.WriteString("  let current = pathname;\n")
	b.WriteString("  let target = null;\n")
	b.WriteString("  for (let left = pathname.split(\"/\").length; left > 0; left--) {\n")
	b.WriteString("    const next = legacyStep(current);\n")
	b.WriteString("    if (next === null || next === current) break;\n")
	b.WriteString("    target = next;\n")
	b.WriteString("    current = next;\n")
	b.WriteString("  }\n")
	b.WriteString("  return target;\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("// The absolute URL a request is redirected to, or null to serve it.\n")
	b.WriteString("// One hop: a historical path arriving on a non-canonical host is\n")
	b.WriteString("// resolved before the redirect, never in a second one.\n")
	b.WriteString("export function routeRequest(requestUrl) {\n")
	b.WriteString("  const url = new URL(requestUrl);\n")
	b.WriteString("  const offHost = url.hostname !== CANONICAL_HOST;\n")
	b.WriteString("  const prefix = offHost ? (HOST_PREFIXES.get(url.hostname) || \"\") : \"\";\n")
	b.WriteString("  const pathname = prefix + url.pathname;\n")
	b.WriteString("  const legacy = legacyTarget(pathname);\n")
	b.WriteString("  if (legacy !== null) return CANONICAL_BASE + legacy + url.search;\n")
	b.WriteString("  if (offHost) return CANONICAL_BASE + pathname + url.search;\n")
	b.WriteString("  return null;\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export default {\n")
	b.WriteString("  async fetch(request, env) {\n")
	b.WriteString("    const target = routeRequest(request.url);\n")
	b.WriteString("    if (target !== null) return Response.redirect(target, 301);\n")
	b.WriteString("    return env.ASSETS.fetch(request);\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

// jsStringArray renders a deduplicated, sorted list of strings the way
// Python's default json.dumps did -- ", " between elements, "[]" when empty.
func jsStringArray(values []string) string {
	seen := map[string]bool{}
	unique := make([]string, 0, len(values))
	for _, value := range values {
		if !seen[value] {
			seen[value] = true
			unique = append(unique, value)
		}
	}
	sort.Strings(unique)
	quoted := make([]string, len(unique))
	for index, value := range unique {
		quoted[index] = util.PythonJSONString(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}
