
[[releasables]]
name = "selfdoc"
tag_format = "v{version}"

[[releasables]]
name = "selfdoc-core"

[[releasables]]
name = "selfblog"

[[projects]]
path = "selfdoc_core/"
name = "selfdoc-core"
library = true
releasable = "selfdoc-core"
watch = ["selfdoc_core/**"]
