// Package html converts Markdown to the HTML a built page's body carries.
//
// It is the converter half of selfdoc's page rendering: block tokens in,
// body HTML out, plus the pieces that operate on that HTML afterwards --
// heading anchors, the glossary's definition sites and cross-page term
// links, internal link rewriting, the syntax-highlight stylesheet, and the
// JavaScript minifier. The page chrome that wraps a body -- navigation,
// table of contents, breadcrumbs, SEO tags, pickers -- is built on top of
// this package rather than inside it.
//
// # Heading anchors are decided once
//
// [AssignHeadingAnchors] is the one place a heading's element id is
// decided. The renderer emits those ids and the search index links to
// them, so a repeated heading gets "setup", "setup-1", "setup-2" in both.
// Because the input is the block token list, a "#"-prefixed line inside a
// fenced code block is code and never becomes an anchor.
//
// # Highlighting
//
// Code blocks are highlighted at build time by chroma, and the stylesheet
// that paints them is generated by [GeneratePygmentsCSS] as one set of
// custom properties defined three times over -- the default scheme, an
// explicitly chosen dark one, and the system fallback for a reader who has
// recorded no preference -- referenced by one scheme-agnostic set of
// rules. A token's colour is therefore a value in the token layer, and the
// two schemes cannot drift apart rule by rule.
//
// Chroma replaces the Pygments this package's Python predecessor used, so
// the emitted token class names are chroma's. Everything else about the
// stylesheet's shape is unchanged.
package html
