#!/usr/bin/env python3
"""Move one repository onto selfdoc's .stricttools/ layout.

selfdoc keeps every directory it owns under one hidden directory at the
repository root: the handwritten pages at .stricttools/docs/, the generated
pages and the rest of the generated-and-committed state at
.stricttools/docs-state/, the build output and the version cache at
.stricttools/docs-cache/, the posts at .stricttools/posts/, and the vocabulary
at .stricttools/vocabulary/. There is no migrator inside selfdoc and no dual
reading: a repository is moved once, by hand, with this script, and every
selfdoc command refuses it until it is.

The script never creates .stricttools/ itself. The directory and its
OWNERS.csv are the repository's own grant of permission, so it refuses when
they are absent and prints the exact rows to write.

What it does, in order:

  1. Reads selfdoc.json for the paths the repository declares today.
  2. Captures the site's current URL set from the sitemap the last build wrote,
     keeping a copy under .stricttools/docs-cache/, so the same set can be
     demanded of the build that follows the move.
  3. Moves every tracked file with 'safegit mv' as ONE commit: a page carrying
     selfdoc's generated-page marker goes to the generated pages directory,
     every other page goes to the handwritten one, and the rest of the old
     tool-state directory goes to its function directory.
  4. Rewrites the paths the moved content names -- the config keys, the root
     ignore file, and the old paths spelled inside pages, posts and templates
     -- as a SECOND commit through 'safegit commit'.
  5. Builds the site again and refuses to finish unless the URL set is
     identical to the one captured in step 2. The commits stay in place; the
     difference is printed.

Usage:

    python3 scripts/move-to-stricttools-layout.py --dry-run
    python3 scripts/move-to-stricttools-layout.py --apply
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT_DIR = ".stricttools"
OWNERS_FILE = "OWNERS.csv"
OWNERS_HEADER = "directory,owner"
OWNER = "selfdoc"
DEPRECATED_ROOT = ".selfdoc"
GENERATED_MARKER_PREFIX = "<!-- generated by selfdoc gen"

DOCS_REL = f"{ROOT_DIR}/docs"
DOCS_STATE_REL = f"{ROOT_DIR}/docs-state"
DOCS_CACHE_REL = f"{ROOT_DIR}/docs-cache"
POSTS_REL = f"{ROOT_DIR}/posts"
VOCABULARY_REL = f"{ROOT_DIR}/vocabulary"
GENERATED_PAGES_REL = f"{DOCS_STATE_REL}/pages"
OUTPUT_REL = f"{DOCS_CACHE_REL}/build"
VERSIONS_REL = f"{DOCS_CACHE_REL}/versions"

REQUIRED_ROWS = [
    OWNERS_HEADER,
    f"docs,{OWNER}",
    f"docs-state,{OWNER}",
    f"docs-cache,{OWNER}",
    f"posts,{OWNER}",
    f"vocabulary,{OWNER}",
]

# The file the pre-move URL set is kept in, inside the uncommitted cache.
SITEMAP_CAPTURE = f"{DOCS_CACHE_REL}/sitemap-before-move.xml"

# The state files the old tool-state directory held, and where each one lives
# now.
STATE_FILES = {
    "manifest.json": f"{DOCS_STATE_REL}/manifest.json",
    "post-manifest.json": f"{DOCS_STATE_REL}/post-manifest.json",
    "revisions.json": f"{DOCS_STATE_REL}/revisions.json",
}
STATE_DIRS = {
    "hashes": f"{DOCS_STATE_REL}/hashes",
    "data": f"{DOCS_STATE_REL}/data",
}


class Refusal(Exception):
    """A condition the person running the script has to clear first."""


def run(argv: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(argv, cwd=cwd, capture_output=True, text=True)


def load_config(project: Path) -> dict:
    path = project / "selfdoc.json"
    if not path.is_file():
        raise Refusal(f"{path} does not exist, so this is not a selfdoc project.")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except ValueError as error:
        raise Refusal(f"{path} is not valid JSON: {error}") from error


def declared_paths(config: dict) -> tuple[str, str, str]:
    """The docs, output and posts paths the repository declares today."""
    docs = config.get("docs") or "docs/"
    output = config.get("output") or "docs/_build/"
    posts = ".selfdoc/posts/"
    block = config.get("posts")
    if isinstance(block, dict) and isinstance(block.get("dir"), str):
        posts = block["dir"]
    return docs.rstrip("/"), output.rstrip("/"), posts.rstrip("/")


def require_owners(project: Path) -> None:
    owners = project / ROOT_DIR / OWNERS_FILE
    if not owners.is_file():
        rows = "\n".join(REQUIRED_ROWS)
        raise Refusal(
            f"{ROOT_DIR}/{OWNERS_FILE} does not exist. This script never creates it: the "
            f"directory and its ownership rows are the repository's own grant. Create "
            f"{ROOT_DIR}/ and write {OWNERS_FILE} with these lines, then run this again:\n"
            f"{rows}"
        )
    declared = {}
    seen_header = False
    for number, line in enumerate(owners.read_text(encoding="utf-8").splitlines(), start=1):
        text = line.strip()
        if not text:
            continue
        if not seen_header:
            if text != OWNERS_HEADER:
                raise Refusal(
                    f"{owners} line {number}: the first line must be the header "
                    f"{OWNERS_HEADER!r}, not {text!r}"
                )
            seen_header = True
            continue
        fields = [field.strip() for field in text.split(",")]
        if len(fields) != 2:
            raise Refusal(f"{owners} line {number}: a row is '{OWNERS_HEADER}'; got {text!r}")
        declared[fields[0]] = fields[1]
    missing = [row for row in REQUIRED_ROWS[1:] if declared.get(row.split(",")[0]) != OWNER]
    if missing:
        raise Refusal(
            f"{owners} does not name {OWNER} as the owner of every directory it needs. "
            f"Add:\n" + "\n".join(missing)
        )


def tracked_files(project: Path, prefix: str) -> list[str]:
    """Every tracked path under prefix, as repository-relative slash paths."""
    result = run(["git", "ls-files", "-z", "--", prefix], project)
    if result.returncode != 0:
        raise Refusal(f"git ls-files {prefix} failed: {result.stderr.strip()}")
    return [name for name in result.stdout.split("\0") if name]


def untracked_entries(project: Path, prefix: str) -> list[str]:
    """Every file under prefix that git does not track, ignored ones included."""
    if not (project / prefix).exists():
        return []
    found = []
    for path in sorted((project / prefix).rglob("*")):
        if path.is_dir():
            continue
        relative = path.relative_to(project).as_posix()
        result = run(["git", "ls-files", "--error-unmatch", "--", relative], project)
        if result.returncode != 0:
            found.append(relative)
    return found


def is_generated_page(path: Path) -> bool:
    try:
        return GENERATED_MARKER_PREFIX in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def plan_moves(project: Path, docs_rel: str, output_rel: str, posts_rel: str) -> list[tuple[str, str]]:
    """Every move the layout needs, as (old, new) repository-relative pairs."""
    moves: list[tuple[str, str]] = []

    for name in tracked_files(project, docs_rel):
        if name == docs_rel or name.startswith(output_rel + "/"):
            continue
        relative = name[len(docs_rel) + 1:]
        if name.endswith(".md") and is_generated_page(project / name):
            moves.append((name, f"{GENERATED_PAGES_REL}/{relative}"))
        else:
            moves.append((name, f"{DOCS_REL}/{relative}"))

    for name in tracked_files(project, posts_rel):
        relative = name[len(posts_rel) + 1:]
        moves.append((name, f"{POSTS_REL}/{relative}"))

    for name in tracked_files(project, DEPRECATED_ROOT):
        if posts_rel and (name == posts_rel or name.startswith(posts_rel + "/")):
            continue
        relative = name[len(DEPRECATED_ROOT) + 1:]
        head = relative.split("/", 1)[0]
        if relative in STATE_FILES:
            moves.append((name, STATE_FILES[relative]))
        elif head in STATE_DIRS:
            moves.append((name, f"{STATE_DIRS[head]}/{relative[len(head) + 1:]}"))
        elif head == "cache":
            moves.append((name, f"{VERSIONS_REL}/{relative[len('cache') + 1:]}"))
        else:
            moves.append((name, f"{DOCS_STATE_REL}/{relative}"))

    return moves


def capture_sitemap(project: Path, output_rel: str, apply: bool) -> set[str]:
    """The URL set the site publishes today, kept for the comparison after."""
    capture = project / SITEMAP_CAPTURE
    built = project / output_rel / "sitemap.xml"
    if built.is_file():
        if apply:
            capture.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(built, capture)
        return sitemap_urls(built)
    if capture.is_file():
        return sitemap_urls(capture)
    raise Refusal(
        f"{output_rel}/sitemap.xml does not exist, so the URL set this move must preserve "
        f"is unknown. Build the site once with a selfdoc release that predates the layout "
        f"flip -- 'go run github.com/smm-h/selfdoc@v0.41.0 build' -- and run this again."
    )


def sitemap_urls(path: Path) -> set[str]:
    tree = ElementTree.parse(path)
    return {
        (element.text or "").strip()
        for element in tree.iter()
        if element.tag.endswith("loc") and (element.text or "").strip()
    }


def rewrite_map(docs_rel: str, output_rel: str, posts_rel: str) -> list[tuple[str, str]]:
    """The literal path rewrites the moved content needs, longest first."""
    pairs = [
        (f"{DEPRECATED_ROOT}/post-manifest.json", f"{DOCS_STATE_REL}/post-manifest.json"),
        (f"{DEPRECATED_ROOT}/manifest.json", f"{DOCS_STATE_REL}/manifest.json"),
        (f"{DEPRECATED_ROOT}/revisions.json", f"{DOCS_STATE_REL}/revisions.json"),
        (f"{DEPRECATED_ROOT}/hashes/", f"{DOCS_STATE_REL}/hashes/"),
        (f"{DEPRECATED_ROOT}/data/", f"{DOCS_STATE_REL}/data/"),
        (f"{DEPRECATED_ROOT}/cache/", f"{VERSIONS_REL}/"),
        (f"{posts_rel}/", f"{POSTS_REL}/"),
        (f"{output_rel}/", f"{OUTPUT_REL}/"),
        (f"{docs_rel}/", f"{DOCS_REL}/"),
    ]
    # A repository already spelling a path the new way needs no rewrite for it.
    return [(old, new) for old, new in pairs if old != new]


REWRITABLE_SUFFIXES = {".md", ".toml", ".json", ".txt"}


def rewritable_files(project: Path, moves: list[tuple[str, str]]) -> list[tuple[Path, str]]:
    """The files whose text may name a moved path, each as (file to read, the
    name it will have once the moves are done).

    A dry run reads the moved content where it still sits, and reports the
    rewrite under the name the move gives it, so the preview covers every file
    the apply run will touch rather than only the ones that never move.
    """
    found = []
    for name in ("selfdoc.json", ".gitignore", "README.md", "CLAUDE.md"):
        path = project / name
        if path.is_file():
            found.append((path, name))
    moved = {new for _, new in moves}
    for old, new in moves:
        if Path(new).suffix not in REWRITABLE_SUFFIXES:
            continue
        source = project / old
        if not source.is_file():
            source = project / new
        if source.is_file():
            found.append((source, new))
    # A file that already sits at its final place and was not moved.
    for prefix in (DOCS_REL, GENERATED_PAGES_REL, POSTS_REL):
        root = project / prefix
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            relative = path.relative_to(project).as_posix()
            if path.is_file() and path.suffix in REWRITABLE_SUFFIXES and relative not in moved:
                found.append((path, relative))
    return found


def plan_rewrites(
    project: Path, pairs: list[tuple[str, str]], moves: list[tuple[str, str]], output_rel: str
) -> list[tuple[str, str, str]]:
    """Every (name, before, after) rewrite, one entry per changed file."""
    planned = []
    for path, name in rewritable_files(project, moves):
        try:
            before = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        after = before
        if name == ".gitignore":
            # The root ignore file's line for the old build output goes
            # rather than being rewritten: the derived ignore file inside the
            # tool-state directory covers the new one.
            after = drop_stale_ignore_lines(after, output_rel)
        for old, new in pairs:
            after = after.replace(old, new)
        if after != before:
            planned.append((name, before, after))
    return planned


def changed_lines(before: str, after: str) -> list[str]:
    """The rewrite as a unified diff, body lines only.

    A line-by-line pairing would misreport every line after a dropped one, so
    the report is a real diff.
    """
    diff = difflib.unified_diff(
        before.split("\n"), after.split("\n"), lineterm="", n=0)
    return [line for line in diff if not line.startswith(("---", "+++"))]


def drop_stale_ignore_lines(text: str, output_rel: str) -> str:
    """The root ignore file's line for the old build output is not needed: the
    derived ignore file inside the tool-state directory covers the new one."""
    kept = []
    for line in text.split("\n"):
        if line.strip().rstrip("/") == output_rel:
            continue
        kept.append(line)
    return "\n".join(kept)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true",
                      help="print every move and every rewrite, and change nothing")
    mode.add_argument("--apply", action="store_true",
                      help="perform the moves and the rewrites, as two commits")
    parser.add_argument("--project", default=".",
                        help="the repository to move; defaults to the working directory")
    parser.add_argument("--selfdoc", default="./bin/selfdoc",
                        help="the selfdoc binary the after-the-move build runs, relative to "
                             "the project or absolute; defaults to ./bin/selfdoc")
    parser.add_argument("--expect-moves", type=int, default=None,
                        help="fail unless the plan holds exactly this many moves")
    args = parser.parse_args()

    project = Path(args.project).resolve()
    try:
        return move(project, args)
    except Refusal as refusal:
        print(f"refused: {refusal}", file=sys.stderr)
        return 1


def move(project: Path, args) -> int:
    config = load_config(project)
    docs_rel, output_rel, posts_rel = declared_paths(config)
    require_owners(project)

    leftovers = []
    for prefix in (docs_rel, posts_rel, DEPRECATED_ROOT):
        for name in untracked_entries(project, prefix):
            if name.startswith(output_rel + "/"):
                continue
            leftovers.append(name)
    if leftovers:
        listed = "\n  ".join(sorted(set(leftovers)))
        raise Refusal(
            "these files are not tracked by git, so they cannot be moved with the rest:\n  "
            f"{listed}\nDelete what is regenerable (the caches) with "
            "'saferm delete -r --on-error abort --description \"pre-move cleanup\" <path>', "
            "or commit what is not, and run this again."
        )

    urls_before = capture_sitemap(project, output_rel, args.apply)
    moves = plan_moves(project, docs_rel, output_rel, posts_rel)
    pairs = rewrite_map(docs_rel, output_rel, posts_rel)

    print(f"project: {project}")
    print(f"declared today: docs={docs_rel}/ output={output_rel}/ posts={posts_rel}/")
    print(f"sitemap URLs captured: {len(urls_before)}")
    print(f"moves planned: {len(moves)}")
    for old, new in moves:
        print(f"  {old} -> {new}")
    if args.expect_moves is not None and len(moves) != args.expect_moves:
        raise Refusal(f"planned {len(moves)} moves, expected {args.expect_moves}")
    if not moves:
        raise Refusal("nothing to move: no tracked file sits at any of the old paths.")

    if args.apply:
        perform_moves(project, moves)

    rewrites = plan_rewrites(project, pairs, moves, output_rel)
    print(f"files to rewrite: {len(rewrites)}")
    for relative, before, after in rewrites:
        diff = changed_lines(before, after)
        print(f"  {relative}: {len(diff)} diff line(s)")
        for line in diff[:30]:
            print(f"    {line}")

    if not args.apply:
        print("dry run: nothing was moved and nothing was written.")
        return 0

    perform_rewrites(project, rewrites, output_rel)
    return verify_urls(project, args.selfdoc, urls_before)


def perform_moves(project: Path, moves: list[tuple[str, str]]) -> None:
    argv = ["safegit", "mv", "--create-missing-directories",
            "-m", "layout: move selfdoc's directories under .stricttools/"]
    argv += [f"{old} -> {new}" for old, new in moves]
    result = run(argv, project)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        raise Refusal(f"safegit mv failed with status {result.returncode}")


def perform_rewrites(project: Path, rewrites, output_rel: str) -> None:
    written = []
    for name, _, after in rewrites:
        (project / name).write_text(after, encoding="utf-8")
        written.append(name)
    # The ownership grant is part of the repository, so it travels with the
    # move rather than being left untracked beside it.
    owners = f"{ROOT_DIR}/{OWNERS_FILE}"
    if run(["git", "ls-files", "--error-unmatch", "--", owners], project).returncode != 0:
        written.append(owners)
    if not written:
        print("no content rewrite was needed.")
        return
    argv = ["safegit", "commit", "-m",
            "layout: name the .stricttools/ paths in the moved content", "--"] + written
    result = run(argv, project)
    sys.stdout.write(result.stdout)
    sys.stderr.write(result.stderr)
    if result.returncode != 0:
        raise Refusal(f"safegit commit failed with status {result.returncode}")


def print_followups(project: Path) -> None:
    """The two things the person does after a successful move."""
    print("two things are left to do by hand:")
    print(f"  commit the ignore file the build derived: "
          f"safegit commit -m \"layout: the derived ignore file\" -- {ROOT_DIR}/.gitignore")
    print("  delete what the old layout left behind (build output, caches), for example:")
    print("    saferm delete -r --on-error abort --description \"superseded by the "
          ".stricttools layout\" docs/_build .selfdoc")


def verify_urls(project: Path, selfdoc: str, urls_before: set[str]) -> int:
    binary = selfdoc if os.path.isabs(selfdoc) else str(project / selfdoc)
    result = run([binary, "build", "--no-auto-commit"], project)
    sys.stdout.write(result.stdout[-4000:])
    sys.stderr.write(result.stderr[-4000:])
    if result.returncode != 0:
        raise Refusal(
            "the build after the move failed. The two commits are in place; fix the "
            "build and compare the sitemap yourself."
        )
    built = project / OUTPUT_REL / "sitemap.xml"
    if not built.is_file():
        raise Refusal(
            f"the build wrote no {OUTPUT_REL}/sitemap.xml, so the URL set cannot be "
            "compared. The two commits are in place."
        )
    urls_after = sitemap_urls(built)
    if urls_after == urls_before:
        print(f"the URL set is unchanged: {len(urls_after)} addresses.")
        print_followups(project)
        return 0
    for url in sorted(urls_before - urls_after):
        print(f"  lost: {url}")
    for url in sorted(urls_after - urls_before):
        print(f"  new:  {url}")
    raise Refusal(
        "the move changed the site's URL set. The two commits are in place; the "
        "differences are listed above."
    )


if __name__ == "__main__":
    raise SystemExit(main())
