package internal_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/smm-h/selfdoc/internal/testproject"
	"github.com/smm-h/stricttest/go/hygiene"
)

// The layout move script is scripts/move-to-stricttools-layout.py: the one-way
// move of a repository's selfdoc directories under .stricttools/, run by hand
// per repository. These cases drive the real script over a real git repository,
// so the script and the layout the engine reads cannot drift apart.

const moveScript = "scripts/move-to-stricttools-layout.py"

func requireSafegit(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("safegit"); err != nil {
		t.Skip("safegit is not on PATH: the move script commits through it")
	}
}

// sitemapXML is a sitemap naming the given addresses.
func sitemapXML(urls ...string) string {
	body := `<?xml version="1.0" encoding="UTF-8"?>` + "\n" +
		`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` + "\n"
	for _, url := range urls {
		body += "  <url><loc>" + url + "</loc></url>\n"
	}
	return body + "</urlset>\n"
}

// oldLayoutProject is a committed repository laid out the way selfdoc used to
// lay one out: pages and build output under docs/, state and posts under
// .selfdoc/.
func oldLayoutProject(t *testing.T) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "project")
	testproject.MkdirAll(t, dir)
	testproject.WriteJSON(t, filepath.Join(dir, "selfdoc.json"), testproject.DefaultConfig(map[string]any{
		"docs":       "docs/",
		"output":     "docs/_build/",
		"root_files": []any{"docs/_README.md"},
	}))
	testproject.WriteText(t, filepath.Join(dir, ".gitignore"), "docs/_build/\n")
	testproject.WriteText(t, filepath.Join(dir, "src", "__init__.py"), `"""Example."""`+"\n")
	testproject.WriteText(t, filepath.Join(dir, "docs", "index.md"),
		"# Home\n\nThe guide is at [the guide](guide/), and the template is docs/_README.md.\n")
	testproject.WriteText(t, filepath.Join(dir, "docs", "guide.md"), "# Guide\n\nHandwritten.\n")
	testproject.WriteText(t, filepath.Join(dir, "docs", "_README.md"), "# Readme template\n")
	testproject.WriteText(t, filepath.Join(dir, "docs", "api.md"),
		"+++\ntitle = \"API\"\ngenerated = true\n+++\n"+
			"<!-- generated by selfdoc gen, do not edit -->\n\n# API\n")
	testproject.WriteText(t, filepath.Join(dir, ".selfdoc", "manifest.json"), "{\"pages\": {}}\n")
	testproject.WriteText(t, filepath.Join(dir, ".selfdoc", "hashes", "hashes.json"), "{}\n")
	testproject.WriteText(t, filepath.Join(dir, ".selfdoc", "posts", "hello.md"),
		"+++\ntitle = \"Hello\"\n+++\n\nA post that names docs/index.md.\n")

	testproject.Git(t, dir, "init", "--quiet")
	testproject.Git(t, dir, "add", ".")
	testproject.Git(t, dir, "commit", "--quiet", "-m", "initial")

	// The build output the last build wrote, which is where the URL set the
	// move must preserve comes from. It is ignored, not tracked.
	testproject.WriteText(t, filepath.Join(dir, "docs", "_build", "sitemap.xml"),
		sitemapXML("https://example.com/", "https://example.com/guide/"))
	return dir
}

// grantOwnership writes the rows that let selfdoc own its directories here.
func grantOwnership(t *testing.T, dir string) {
	t.Helper()
	testproject.WriteText(t, filepath.Join(dir, ".stricttools", "OWNERS.csv"),
		"directory,owner\ndocs,selfdoc\ndocs-state,selfdoc\ndocs-cache,selfdoc\nposts,selfdoc\n")
}

// fakeSelfdoc installs a stub binary that writes the given sitemap where a
// build would, so the script's URL comparison is exercised without a real
// build. The real build is what this repository's own move ran.
func fakeSelfdoc(t *testing.T, dir, sitemap string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "fake-selfdoc")
	script := "#!/bin/sh\n" +
		"mkdir -p .stricttools/docs-cache/build\n" +
		"cat > .stricttools/docs-cache/build/sitemap.xml <<'SITEMAP'\n" +
		sitemap +
		"SITEMAP\n"
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		t.Fatalf("writing the stub: %v", err)
	}
	return path
}

// runMove runs the move script over dir and returns its output and status.
func runMove(t *testing.T, root, dir string, args ...string) (string, int) {
	t.Helper()
	argv := append([]string{filepath.Join(root, moveScript), "--project", dir}, args...)
	cmd := exec.Command("python3", argv...)
	cmd.Dir = root
	out, err := cmd.CombinedOutput()
	status := 0
	var exitErr *exec.ExitError
	if err != nil {
		if !asExitError(err, &exitErr) {
			t.Fatalf("running the move script: %v\n%s", err, out)
		}
		status = exitErr.ExitCode()
	}
	return string(out), status
}

func TestTheMoveScriptRefusesARepositoryThatGrantedNothing(t *testing.T) {
	requirePython3(t)
	hygiene.Isolate(t)
	root := moduleRoot(t)
	dir := oldLayoutProject(t)

	out, status := runMove(t, root, dir, "--dry-run")
	if status == 0 {
		t.Fatalf("the script moved a repository that granted no ownership:\n%s", out)
	}
	for _, want := range []string{".stricttools/OWNERS.csv", "directory,owner", "docs-state,selfdoc"} {
		if !strings.Contains(out, want) {
			t.Errorf("the refusal does not carry %q:\n%s", want, out)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".stricttools", "docs")); !os.IsNotExist(err) {
		t.Errorf("the script created a directory anyway (stat err = %v)", err)
	}
}

func TestTheMoveScriptDryRunChangesNothing(t *testing.T) {
	requirePython3(t)
	hygiene.Isolate(t)
	root := moduleRoot(t)
	dir := oldLayoutProject(t)
	grantOwnership(t, dir)

	out, status := runMove(t, root, dir, "--dry-run", "--expect-moves", "7")
	if status != 0 {
		t.Fatalf("the dry run refused:\n%s", out)
	}
	for _, want := range []string{
		"docs/api.md -> .stricttools/docs-state/pages/api.md",
		"docs/index.md -> .stricttools/docs/index.md",
		"docs/_README.md -> .stricttools/docs/_README.md",
		".selfdoc/posts/hello.md -> .stricttools/posts/hello.md",
		".selfdoc/manifest.json -> .stricttools/docs-state/manifest.json",
		".selfdoc/hashes/hashes.json -> .stricttools/docs-state/hashes/hashes.json",
		"sitemap URLs captured: 2",
		"files to rewrite:",
		"dry run: nothing was moved",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("the dry run does not report %q:\n%s", want, out)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, ".stricttools", "docs", "index.md")); !os.IsNotExist(err) {
		t.Errorf("the dry run moved a page (stat err = %v)", err)
	}
	if got := testproject.ReadText(t, filepath.Join(dir, "selfdoc.json")); !strings.Contains(got, `"docs": "docs/"`) {
		t.Errorf("the dry run rewrote the config:\n%s", got)
	}
}

func TestTheMoveScriptRefusesAWrongExpectedCount(t *testing.T) {
	requirePython3(t)
	hygiene.Isolate(t)
	root := moduleRoot(t)
	dir := oldLayoutProject(t)
	grantOwnership(t, dir)

	out, status := runMove(t, root, dir, "--dry-run", "--expect-moves", "99")
	if status == 0 {
		t.Fatalf("a wrong expected count was accepted:\n%s", out)
	}
	if !strings.Contains(out, "expected 99") {
		t.Errorf("the refusal does not name the mismatch:\n%s", out)
	}
}

func TestTheMoveScriptMovesAndRewrites(t *testing.T) {
	requirePython3(t)
	requireSafegit(t)
	hygiene.Isolate(t)
	root := moduleRoot(t)
	dir := oldLayoutProject(t)
	grantOwnership(t, dir)
	stub := fakeSelfdoc(t, dir, sitemapXML("https://example.com/", "https://example.com/guide/"))

	out, status := runMove(t, root, dir, "--apply", "--selfdoc", stub)
	if status != 0 {
		t.Fatalf("the move refused:\n%s", out)
	}

	for _, want := range []string{
		".stricttools/docs/index.md",
		".stricttools/docs/guide.md",
		".stricttools/docs/_README.md",
		".stricttools/docs-state/pages/api.md",
		".stricttools/docs-state/manifest.json",
		".stricttools/docs-state/hashes/hashes.json",
		".stricttools/posts/hello.md",
	} {
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(want))); err != nil {
			t.Errorf("%s was not moved: %v", want, err)
		}
	}
	for _, gone := range []string{"docs/index.md", ".selfdoc/manifest.json", ".selfdoc/posts/hello.md"} {
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(gone))); !os.IsNotExist(err) {
			t.Errorf("%s is still there (stat err = %v)", gone, err)
		}
	}

	config := testproject.ReadText(t, filepath.Join(dir, "selfdoc.json"))
	for _, want := range []string{
		`"docs": ".stricttools/docs/"`,
		`"output": ".stricttools/docs-cache/build/"`,
		`".stricttools/docs/_README.md"`,
	} {
		if !strings.Contains(config, want) {
			t.Errorf("the config does not carry %q:\n%s", want, config)
		}
	}
	// A path spelled inside the moved content is rewritten too.
	page := testproject.ReadText(t, filepath.Join(dir, ".stricttools", "docs", "index.md"))
	if !strings.Contains(page, ".stricttools/docs/_README.md") {
		t.Errorf("the page still names the old path:\n%s", page)
	}
	post := testproject.ReadText(t, filepath.Join(dir, ".stricttools", "posts", "hello.md"))
	if !strings.Contains(post, ".stricttools/docs/index.md") {
		t.Errorf("the post still names the old path:\n%s", post)
	}
	// The root ignore file's line for the old build output is dropped: the
	// derived ignore file inside the tool-state directory covers the new one.
	ignore := testproject.ReadText(t, filepath.Join(dir, ".gitignore"))
	if strings.Contains(ignore, "docs/_build/") {
		t.Errorf("the root ignore file still names the old build output:\n%s", ignore)
	}

	// Two commits: the moves, then the rewrites.
	log := gitOutput(t, dir, "log", "--format=%s", "-3")
	subjects := strings.Split(strings.TrimSpace(log), "\n")
	if len(subjects) < 3 ||
		!strings.Contains(subjects[0], "name the .stricttools/ paths") ||
		!strings.Contains(subjects[1], "move selfdoc's directories") {
		t.Errorf("the commits are %v, want the rewrites over the moves", subjects)
	}
	// Nothing the move touched is left uncommitted: the grant travels with
	// it, and what remains is the old build output, which the closing report
	// tells the person to delete.
	for _, line := range strings.Split(gitStatus(t, dir), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasSuffix(trimmed, "docs/") ||
			strings.HasSuffix(trimmed, ".stricttools/docs-cache/") {
			continue
		}
		t.Errorf("the move left %q uncommitted", trimmed)
	}
	if !strings.Contains(out, "saferm delete") {
		t.Errorf("the run does not say what to delete:\n%s", out)
	}
	if !strings.Contains(out, "the URL set is unchanged: 2 addresses") {
		t.Errorf("the run does not report the URL comparison:\n%s", out)
	}
}

func TestTheMoveScriptRefusesAChangedURLSet(t *testing.T) {
	requirePython3(t)
	requireSafegit(t)
	hygiene.Isolate(t)
	root := moduleRoot(t)
	dir := oldLayoutProject(t)
	grantOwnership(t, dir)
	stub := fakeSelfdoc(t, dir, sitemapXML("https://example.com/", "https://example.com/moved/"))

	out, status := runMove(t, root, dir, "--apply", "--selfdoc", stub)
	if status == 0 {
		t.Fatalf("a move that changed the URL set was accepted:\n%s", out)
	}
	for _, want := range []string{
		"lost: https://example.com/guide/",
		"new:  https://example.com/moved/",
		"the move changed the site's URL set",
		"The two commits are in place",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("the refusal does not carry %q:\n%s", want, out)
		}
	}
	// The commits stay: the refusal is about the outcome, not a rollback.
	if _, err := os.Stat(filepath.Join(dir, ".stricttools", "docs", "index.md")); err != nil {
		t.Errorf("the moves were rolled back: %v", err)
	}
}

// gitOutput runs a read-only git command and returns its standard output.
func gitOutput(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("git %v: %v", args, err)
	}
	return string(out)
}

func gitStatus(t *testing.T, dir string) string {
	t.Helper()
	return strings.TrimSpace(gitOutput(t, dir, "status", "--porcelain"))
}
