"""First-class support for strictcli-based projects.

Reads `.strictcli/schema.json` (generated by `<app> --dump-schema`) for CLI
structure (App, commands, flags, args, groups), and produces Markdown
documentation pages.

The reader is **schema version 2 only**.  v2 is not a superset of v1: it
deletes the ``type``, ``repeatable`` and arg-level ``required`` keys the v1
reader read, and adds constructs (selectors, constraints, update
declarations) v1 had no encoding for.  A schema of any other version is a
hard error naming the regeneration command, because the alternative --
reading a v1 file with v2 rules -- is a page that silently labels every flag
``str`` and every positional argument required.  That page shipped once
already, which is why there is no fallback here.
"""

import json
import os
import re

from selfdoc.utils import _read_project_field, parse_frontmatter as _parse_frontmatter
from selfdoc.tables import render_markdown_table
from selfdoc.utils import atomic_write as _atomic_write
from selfdoc_core.address import root_page_link
from selfdoc_core.prose import first_sentence

from selfdoc_core import effects


# Matches the default per-command/per-group description templates so we can
# detect when a CLI page still has its auto-generated description (and should
# be recomputed) versus when a user has hand-edited the description (and we
# should preserve it).
#
# Templates produced by _render_command_page / _render_group_page when the
# command/group's help text is shorter than 50 characters:
#   "Reference for the {app_name} {name} command — usage, flags, arguments,
#    and examples for the {name} subcommand of the {app_name} CLI."
#   "Reference for the {app_name} {gname} command group — subcommands, flags,
#    arguments, and usage details for the {gname} group in the {app_name} CLI."
#
# And the CLI index template:
#   "Complete CLI reference for {app_name} — all available commands,
#    subcommands, flags, arguments, and usage examples with detailed
#    descriptions."
_DEFAULT_CLI_COMMAND_DESC_RE = re.compile(
    r"^Reference for the \S+ \S+ command — "
    r"usage, flags, arguments, and examples for the \S+ subcommand "
    r"of the \S+ CLI\.?$"
)
_DEFAULT_CLI_GROUP_DESC_RE = re.compile(
    r"^Reference for the \S+ \S+ command group — "
    r"subcommands, flags, arguments, and usage details "
    r"for the \S+ group in the \S+ CLI\.?$"
)
_DEFAULT_CLI_INDEX_DESC_RE = re.compile(
    r"^Complete CLI reference for \S+ — "
    r"all available commands, subcommands, flags, arguments, "
    r"and usage examples with detailed descriptions\.?$"
)


# ---------------------------------------------------------------------------
# Default description ownership (public: consumed by selfdoc.ownership)
# ---------------------------------------------------------------------------


def _normalize_cli_description(value):
    """Strip surrounding whitespace and one layer of matching quotes."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        value = value[1:-1].strip()
    return value


def compute_default_cli_description(kind, name, app_name, help_text):
    """Return the machine-default ``description`` for a CLI page.

    ``kind`` is ``"index"``, ``"command"``, or ``"group"``.  When the page's
    help text is long enough (>= 50 chars) the default is the first sentence
    of the help; otherwise a long-form template naming the app and command is
    used.  The index default is always the fixed long-form template.
    """
    if kind == "index":
        return (
            f"Complete CLI reference for {app_name} — "
            f"all available commands, subcommands, flags, arguments, "
            f"and usage examples with detailed descriptions."
        )
    if help_text and len(help_text) >= 50:
        return first_sentence(help_text)
    if kind == "command":
        return (
            f"Reference for the {app_name} {name} command — "
            f"usage, flags, arguments, and examples for the {name} subcommand "
            f"of the {app_name} CLI."
        )
    if kind == "group":
        return (
            f"Reference for the {app_name} {name} command group — "
            f"subcommands, flags, arguments, and usage details "
            f"for the {name} group in the {app_name} CLI."
        )
    raise ValueError(f"unknown CLI page kind: {kind!r}")


def is_default_cli_description(value, *, kind, name=None, app_name="",
                              help_text=None):
    """Return True if *value* is a machine-generated default CLI description.

    Recognizes every historical machine form so machine residue is reseeded
    rather than frozen as handwritten:

    - the current first-sentence form (help >= 50 chars), or
    - the long-form default template (help < 50 chars, or the index), or
    - the historical ``help[:155]`` truncation (with/without a trailing
      ellipsis), or
    - a >= 100-char prefix of the raw help (a truncated default from any
      prior cut point).

    An empty value counts as a machine default (a blank machine placeholder
    the caller should reseed).  CLI machine text is derivable from the schema,
    so this is a live recompute -- no static set can cover the truncated
    prefix family.
    """
    value = _normalize_cli_description(value)
    if not value:
        return True

    # Determine the "default_pattern" exactly as the renderers do so the
    # recognition matches what compute_default_cli_description emits.
    if kind == "index":
        default_pattern = _DEFAULT_CLI_INDEX_DESC_RE
    elif help_text and len(help_text) >= 50:
        default_pattern = first_sentence(help_text)
    elif kind == "command":
        default_pattern = _DEFAULT_CLI_COMMAND_DESC_RE
    elif kind == "group":
        default_pattern = _DEFAULT_CLI_GROUP_DESC_RE
    else:
        raise ValueError(f"unknown CLI page kind: {kind!r}")

    if hasattr(default_pattern, "match"):
        if default_pattern.match(value):
            return True
    elif value == default_pattern:
        return True

    if help_text and kind in ("command", "group"):
        core = value[:-3] if value.endswith("...") else value
        first_line = help_text.split("\n", 1)[0]
        if core == first_line[:155]:
            return True
        if len(core) >= 100 and help_text.startswith(core):
            return True

    return False


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


def uses_strictcli(source_paths, base_dir):
    """Return True if the project has a ``.strictcli/schema.json`` file.

    The *source_paths* parameter is accepted for call-site compatibility
    but is not used -- detection is purely based on the schema file.
    """
    schema_path = os.path.join(base_dir, ".strictcli", "schema.json")
    return os.path.isfile(schema_path)


# ---------------------------------------------------------------------------
# Schema discovery
# ---------------------------------------------------------------------------


class SchemaDiscoveryError(RuntimeError):
    """Raised when ``.strictcli/schema.json`` discovery fails or is ambiguous.

    A hard error (exit 1). Subclasses ``RuntimeError`` so the CLI's existing
    ``RuntimeError`` handlers surface it with a clean message and non-zero exit.
    """


# Directory names never traversed when discovering schemas. Hidden directories
# (leading ``.``) are pruned separately -- ``.strictcli`` is not traversed into
# but is still detected as a schema *location* under each visited directory.
_SCHEMA_DISCOVERY_EXCLUDES: set[str] = {
    "node_modules", "dist", "build", "_build", "target",
    "vendor", "venv", "__pycache__",
}


def discover_schema_dirs(base_dir):
    """Discover directories containing a ``.strictcli/schema.json`` file.

    Walks *base_dir*, pruning vendored/build directories and hidden
    directories (leading ``.``). For every visited directory, checks whether it
    holds a ``.strictcli/schema.json`` and records its path relative to
    *base_dir* (the project root uses ``"."``).

    Returns a sorted list of relative directory paths (each is the directory
    that *contains* the ``.strictcli`` folder, i.e. the value a ``schema-dir``
    attribute would take).
    """
    base_dir = os.path.abspath(base_dir)
    found = []
    for dirpath, dirnames, _filenames in os.walk(base_dir):
        # Prune traversal into vendored/build and hidden directories.
        dirnames[:] = [
            d for d in dirnames
            if d not in _SCHEMA_DISCOVERY_EXCLUDES and not d.startswith(".")
        ]
        schema_path = os.path.join(dirpath, ".strictcli", "schema.json")
        if os.path.isfile(schema_path):
            rel = os.path.relpath(dirpath, base_dir)
            found.append("." if rel == os.curdir else rel)
    return sorted(found)


# ---------------------------------------------------------------------------
# Schema reader
# ---------------------------------------------------------------------------


#: The one dumped-schema format this reader understands.  strictcli 0.41.0
#: writes it; there is no v1 path and no negotiated fallback.
SUPPORTED_SCHEMA_VERSION = 2


def read_schema_json(base_dir, source_paths=None):
    """Read ``.strictcli/schema.json`` and translate to the internal format.

    Returns a dict with ``app_name``, ``app_version``, ``app_help``,
    ``global_flags`` (list), ``infra`` (dict), ``deprecated`` (dict),
    ``config`` (dict of the app-level config declaration), ``commands``
    (list), and ``groups`` (list) -- or ``None`` if the schema file does not
    exist.

    The translation preserves every per-entry field the renderers read
    (``value_schema``, ``presence``, ``default``, ``choices``, ``elect_by``,
    ``nullable``, ``negatable``, ``unique``, ``prefixed``, ``variadic``,
    ``hidden``, ``deprecated``, ``passthrough``, ``flag_sets``,
    ``constraints``, ``update_of``, ``write_mode``) plus the effects-regime
    per-command fields (``effect``, ``consequential``, ``grants``,
    ``dry_run_supported``, ``dry_run_unsupported_reason``), all untouched.

    strictcli omits the app-level ``global_flags``/``infra``/``deprecated``
    keys when they are empty, and some emitters write an explicit ``null``;
    both normalize to empty containers so renderers can truth-test them.

    Raises:
        ValueError: When the file declares a ``schema_version`` other than
            :data:`SUPPORTED_SCHEMA_VERSION`, or carries no ``project_id``,
            or names a different project.
    """
    schema_path = os.path.join(base_dir, ".strictcli", "schema.json")
    if not os.path.isfile(schema_path):
        return None

    with open(schema_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    # The version is read before anything else: every key below is read on
    # v2's terms, and reading a v1 document with them produces a page that
    # is wrong without being empty.
    version = schema.get("schema_version")
    if version != SUPPORTED_SCHEMA_VERSION:
        app_name = schema.get("name", "<app>")
        raise ValueError(
            f"Schema at {schema_path} declares schema_version "
            f"{version!r}; this selfdoc reads schema_version "
            f"{SUPPORTED_SCHEMA_VERSION} only. Regenerate it with a "
            f"strictcli >= 0.41.0: {app_name} --dump-schema"
        )

    # Validate project_id
    project_id = schema.get("project_id")
    if project_id is None:
        app_name = schema.get("name", "<app>")
        raise ValueError(
            f"Schema missing project_id field. "
            f"Regenerate with: {app_name} --dump-schema"
        )
    expected = _read_project_field(base_dir, "name")
    if expected != "unknown" and project_id != expected:
        raise ValueError(
            f"Schema project_id '{project_id}' does not match "
            f"project name '{expected}'. Wrong schema file?"
        )

    result = {
        "app_name": schema.get("name", ""),
        "app_version": schema.get("version", ""),
        "app_help": schema.get("help", ""),
        "global_flags": schema.get("global_flags") or [],
        "infra": schema.get("infra") or {},
        "deprecated": schema.get("deprecated") or {},
        # v2's behavioral-completeness keys.  Each is emitted exactly when
        # the app departs from the framework's own behaviour, so their
        # presence is the whole reason to document them.
        "config": schema.get("config") or False,
        "config_format": schema.get("config_format"),
        "config_path": schema.get("config_path"),
        "config_conflict_mode": schema.get("config_conflict_mode"),
        "env_prefix": schema.get("env_prefix"),
    }

    # Translate commands dict -> list
    commands_dict = schema.get("commands", {})
    result["commands"] = [
        _translate_command(name, cmd)
        for name, cmd in commands_dict.items()
    ]

    # Translate groups dict -> list (with nested commands dict -> list)
    groups_dict = schema.get("groups", {})
    result["groups"] = [
        _translate_group(name, grp)
        for name, grp in groups_dict.items()
    ]

    return result


def _translate_command(name, cmd):
    """Translate a schema command dict to the internal format."""
    translated = dict(cmd)
    # Ensure name is present
    translated.setdefault("name", name)
    return translated


def _translate_group(name, grp):
    """Translate a schema group dict to the internal format."""
    translated = {
        "name": grp.get("name", name),
        "help": grp.get("help", ""),
    }

    # Convert nested commands dict -> list
    commands_dict = grp.get("commands", {})
    translated["commands"] = [
        _translate_command(cname, cmd)
        for cname, cmd in commands_dict.items()
    ]

    # Preserve extra fields
    for key in ("deprecated", "groups"):
        if key in grp:
            translated[key] = grp[key]

    return translated


# ---------------------------------------------------------------------------
# Introspection
# ---------------------------------------------------------------------------


def extract_cli_structure(source_paths, base_dir):
    """Read the CLI structure from ``.strictcli/schema.json``.

    Returns a dict describing the app, its commands, flags, args, and
    groups -- or raises ``FileNotFoundError`` if no schema is found.

    The *source_paths* parameter is accepted for call-site compatibility
    but is not used.
    """
    result = read_schema_json(base_dir, source_paths=source_paths)
    if result is not None:
        return result
    raise FileNotFoundError(
        "No .strictcli/schema.json found in "
        f"{base_dir!r}. Run '<app> --dump-schema' to generate it."
    )


# ---------------------------------------------------------------------------
# Page generation
# ---------------------------------------------------------------------------


def expected_cli_page_filenames(cli_structure):
    """Return the list of filenames ``generate_cli_pages`` would write.

    Used by the stale-file cleanup pass to know which CLI page names are
    "current" so the generated pages from a prior run are not deleted as
    stale before the new pages have been written.
    """
    if cli_structure is None:
        return []
    names = ["cli-index.md"]
    for cmd in cli_structure.get("commands", []):
        names.append(f"cli-{cmd['name']}.md")
    for grp in cli_structure.get("groups", []):
        names.append(f"cli-{grp['name']}.md")
    return names


def _read_existing_cli_description(filepath, *, kind, name, app_name,
                                  help_text=None):
    """Return the hand-edited ``description`` from a CLI page, else ``None``.

    Returns ``None`` (meaning: reseed with the machine default) if the file
    does not exist, has no ``description`` key, has an empty description, or
    still holds a machine-generated default (recognized by
    :func:`is_default_cli_description`).  Any other value is a genuine hand
    edit and is returned verbatim.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except OSError:
        return None

    metadata, _ = _parse_frontmatter(content)
    raw = metadata.get("description")
    if raw is None or not isinstance(raw, str):
        return None

    value = _normalize_cli_description(raw)
    if not value:
        return None

    if is_default_cli_description(
        value, kind=kind, name=name, app_name=app_name, help_text=help_text,
    ):
        return None

    return value


def generate_cli_pages(cli_structure, docs_dir):
    """Generate Markdown documentation pages from *cli_structure*.

    Creates an index page and one page per top-level command group.
    All pages have ``generated: true`` frontmatter and read-only
    permissions (0o444).

    Returns a list of generated filenames (relative to *docs_dir*).
    """
    effects.makedirs(docs_dir, exist_ok=True)
    generated = []

    app_name = cli_structure.get("app_name", "")
    app_help = cli_structure.get("app_help", "")
    app_version = cli_structure.get("app_version", "")
    commands = cli_structure.get("commands", [])
    groups = cli_structure.get("groups", [])

    # -- Index page --
    default_index_desc = compute_default_cli_description(
        "index", None, app_name, None,
    )
    index_path = os.path.join(docs_dir, "cli-index.md")
    existing_index_desc = _read_existing_cli_description(
        index_path, kind="index", name=None, app_name=app_name,
    )
    cli_index_desc = (
        existing_index_desc
        if existing_index_desc is not None
        else default_index_desc
    )
    seeded_index = "seeded: true" if existing_index_desc is None else ""
    index_lines = [
        "---",
        f"title: {app_name} CLI Reference",
        f'description: "{cli_index_desc}"',
        "generated: true",
    ]
    if seeded_index:
        index_lines.append(seeded_index)
    index_lines.extend([
        'nav_group: "CLI Reference"',
        "nav_order: 0",
        "order: 91",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} CLI Reference",
        "",
    ])
    if app_help:
        index_lines.append(app_help)
        index_lines.append("")
    if app_version:
        # A var DIRECTIVE, not the literal version: the raw page body is what
        # staleness hashes, so baking the version in here moved the content
        # hash on every release and tripped STALE001 with zero signal.  The
        # directive resolves at build time, so the site still shows the
        # current version.
        index_lines.append('Version: :-: var key="project.version"')
        index_lines.append("")

    if commands:
        index_lines.append("## Commands")
        index_lines.append("")
        for cmd in commands:
            href = root_page_link(f"cli-{cmd['name']}.md")
            index_lines.append(f"- [{cmd['name']}]({href}) -- {cmd.get('help', '')}")
        index_lines.append("")

    if groups:
        index_lines.append("## Command Groups")
        index_lines.append("")
        for grp in groups:
            href = root_page_link(f"cli-{grp['name']}.md")
            index_lines.append(f"- [{grp['name']}]({href}) -- {grp.get('help', '')}")
        index_lines.append("")

    global_flags = cli_structure.get("global_flags") or []
    if global_flags:
        index_lines.append("## Global flags")
        index_lines.append("")
        index_lines.append(_flag_table(global_flags))
        index_lines.append("")

    if _schema_has_effects(cli_structure):
        index_lines.append("## Framework flags")
        index_lines.append("")
        index_lines.append(_RESERVED_QUARTET_INTRO)
        index_lines.append("")
        index_lines.append(render_markdown_table(
            ["Flag", "Effect"], _RESERVED_QUARTET_ROWS,
        ))
        index_lines.append("")

    index_lines.extend(_config_lines(cli_structure))

    infra = cli_structure.get("infra") or {}
    if infra:
        index_lines.append("## Infrastructure")
        index_lines.append("")
        roots = infra.get("roots") or []
        if roots:
            index_lines.append("### Roots")
            index_lines.append("")
            index_lines.append(_env_table(roots, "Default"))
            index_lines.append("")
        handshakes = infra.get("handshakes") or []
        if handshakes:
            index_lines.append("### Handshake variables")
            index_lines.append("")
            index_lines.append(_env_table(handshakes, "Description"))
            index_lines.append("")
        connections = infra.get("connections") or []
        if connections:
            index_lines.append("### Connection variables")
            index_lines.append("")
            index_lines.append(_env_table(connections, "Description"))
            index_lines.append("")

    deprecated = cli_structure.get("deprecated") or {}
    if deprecated:
        index_lines.append("## Deprecated")
        index_lines.append("")
        for dname in sorted(deprecated):
            index_lines.append(f"- `{dname}` -- {deprecated[dname]}")
        index_lines.append("")

    index_filename = "cli-index.md"
    _write_page(
        os.path.join(docs_dir, index_filename),
        "\n".join(index_lines),
    )
    generated.append(index_filename)

    # Build alphabetical ordering for all command/group pages
    all_names = sorted(
        [cmd["name"] for cmd in commands] + [grp["name"] for grp in groups]
    )
    name_to_nav_order = {name: idx + 1 for idx, name in enumerate(all_names)}

    # -- One page per top-level command --
    for cmd in commands:
        fname = f"cli-{cmd['name']}.md"
        out_path = os.path.join(docs_dir, fname)
        content = _render_command_page(
            cmd, app_name, name_to_nav_order[cmd["name"]],
            existing_path=out_path,
        )
        _write_page(out_path, content)
        generated.append(fname)

    # -- One page per group --
    for grp in groups:
        fname = f"cli-{grp['name']}.md"
        out_path = os.path.join(docs_dir, fname)
        content = _render_group_page(
            grp, app_name, name_to_nav_order[grp["name"]],
            existing_path=out_path,
        )
        _write_page(out_path, content)
        generated.append(fname)

    return generated


def _write_page(filepath, content):
    """Write a generated page atomically with read-only permissions."""
    _atomic_write(filepath, content, permissions=0o444)


# ---------------------------------------------------------------------------
# Effects-regime rendering helpers
# ---------------------------------------------------------------------------


# The framework-owned reserved quartet. These four flags are declared by
# strictcli itself, never by the app, so they appear nowhere in schema.json at
# any level -- the section is static and keyed on the schema carrying `effect`
# fields (a schema with effects is a post-quartet app).
_RESERVED_QUARTET_ROWS = [
    [
        "`--dry-run`",
        "Preview mode: no mutation runs. The framework prints a log of "
        "every effect the command would have performed.",
    ],
    [
        "`--approve-consequential`",
        "Skips the confirmation prompt a consequential command shows "
        "before it runs.",
    ],
    [
        "`--quiet`",
        "Hides informational output. Warnings, errors, structured data "
        "and the dry-run log are never suppressed.",
    ],
    [
        "`--verbose`",
        "Shows debug output. `--quiet` wins when both are passed.",
    ],
]

_RESERVED_QUARTET_INTRO = (
    "These flags are owned by the strictcli framework, not by the app. "
    "No command may declare a flag with one of these names, and each is "
    "recognized anywhere on the command line."
)


def _schema_has_effects(cli_structure):
    """Return True if any command in *cli_structure* declares an ``effect``.

    Classification is mandatory under the effects regime, so a single
    ``effect`` field anywhere proves the app is built on a strictcli that
    owns the reserved quartet.
    """
    for cmd in cli_structure.get("commands", []) or []:
        if cmd.get("effect"):
            return True
    for grp in cli_structure.get("groups", []) or []:
        for cmd in grp.get("commands", []) or []:
            if cmd.get("effect"):
                return True
    return False


def _fmt_default(value):
    """Format a declared default value for table display.

    Every default is rendered, ``""``, ``0``, ``false``, ``[]`` and ``{}``
    included: under the presence declaration a default is emitted exactly
    when ``presence`` is ``"default"``, so an empty-looking value is a
    declaration and not an absence.  Structured defaults -- strictcli's
    ``relative_to_root`` marker and a selector's flat default map -- render
    as compact JSON rather than a Python repr.
    """
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, (dict, list)):
        return f"`{json.dumps(value)}`"
    if value is None:
        return ""
    return f"`{value}`"


#: JSON Schema type names to the words a reader of a CLI page knows.  The
#: fragment subset is closed at four keywords (``type``, ``items``,
#: ``additionalProperties``, ``enum``), so this table plus the two container
#: rules below covers every fragment strictcli can emit.
_SCALAR_WORDS = {
    "string": "str",
    "boolean": "bool",
    "integer": "int",
    "number": "float",
}


def _type_word(value_schema):
    """Render a v2 ``value_schema`` fragment as a readable type word.

    Returns ``""`` for a missing fragment, which is a **selector** -- its
    value is a variant the closed subset cannot express, and its absence is
    the declaration (the caller renders it as the construct it is).
    """
    if not value_schema:
        return ""
    kind = value_schema.get("type")
    if kind == "array":
        item = value_schema.get("items") or {}
        return f"list[{_SCALAR_WORDS.get(item.get('type'), item.get('type', '?'))}]"
    if kind == "object":
        val = value_schema.get("additionalProperties") or {}
        return f"dict[str, {_SCALAR_WORDS.get(val.get('type'), val.get('type', '?'))}]"
    return _SCALAR_WORDS.get(kind, str(kind))


def _presence_cell(entry):
    """Render an entry's presence as the one fact it declares.

    Exactly one of ``required`` / ``optional`` / ``default: <value>``, which
    is what strictcli's own ``--help`` renders per line.  A ``Default``
    column cannot carry three states, and an empty one said nothing about
    which of the two valueless states a flag was in.
    """
    presence = entry.get("presence")
    if presence == "default":
        return f"default: {_fmt_default(entry.get('default'))}"
    if presence in ("required", "optional"):
        return presence
    return ""


def _choices_note(entry):
    """Render a value flag's ``choices`` records as one prose sentence.

    v2 splits a ``choices=`` declaration in two: the values as an ``enum``
    inside ``value_schema``, and the value-plus-help records beside it under
    ``choices``.  The records are the half a reader wants, and ``help`` is
    omitted from an entry that declares none.
    """
    records = entry.get("choices") or []
    if not records or entry.get("elect_by"):
        return ""
    parts = []
    for rec in records:
        value = f"`{rec.get('value')}`"
        chelp = rec.get("help")
        parts.append(f"{value} ({chelp})" if chelp else value)
    return "Values: " + ", ".join(parts) + "."


def _spelled_name(fl):
    """Render every argv spelling one flag declaration mints.

    A negatable bool publishes ``--no-x`` and a nullable property publishes
    ``--unset-x``; neither gets an entry of its own in the dump, exactly as
    ``negatable`` has never published one, so the reader has to be told they
    exist.
    """
    name = fl["name"]
    spellings = [f"`--{name}`"]
    is_bool = (fl.get("value_schema") or {}).get("type") == "boolean"
    if is_bool and fl.get("negatable") is not False:
        spellings.append(f"`--no-{name}`")
    if fl.get("nullable"):
        spellings.append(f"`--unset-{name}`")
    return ", ".join(spellings)


#: Two levels of indentation inside a table cell, for a scoped declaration.
_INDENT = "&nbsp;&nbsp;&nbsp;&nbsp;"


def _describe(fl, prefix=""):
    """Compose a flag's description cell: scope note, help, choices, unset."""
    parts = []
    if prefix:
        parts.append(prefix)
    if fl.get("help"):
        parts.append(fl["help"])
    note = _choices_note(fl)
    if note:
        parts.append(note)
    if fl.get("nullable"):
        parts.append(f"`--unset-{fl['name']}` clears it.")
    if fl.get("prefixed") is False and fl.get("env"):
        parts.append("Its env var is not prefixed with the app's env prefix.")
    return " ".join(parts)


def _flag_rows(flags, depth=0, scope=None):
    """Build flag-table rows for *flags*, recursing through selector scopes.

    A **selector** is an entry carrying ``elect_by``; the presence of that
    key is the discriminator, and such an entry never carries a
    ``value_schema``.  It is rendered as the construct it is rather than as
    an ordinary row:

    - under ``member-flags`` the selector's own name is **never typed** --
      it is only the handler key and the noun errors use -- so its row shows
      the bare name with no ``--`` and each choice becomes a row of its own
      under its own token (``--pattern``), carrying the choice's payload
      type when it has one;
    - under ``selector-token`` the selector's name *is* typed (``--via
      email``), so its row keeps the ``--`` and the choices are listed as
      the values it accepts.

    Either way a choice's scope -- the flags that exist only while it is
    elected -- follows indented, to unlimited depth.  Each scoped row also
    names its scope in prose, so a row read on its own (or after a reader
    sorts the table) still states the condition it lives under.
    """
    rows = []
    pad = _INDENT * depth
    for fl in flags:
        if fl.get("elect_by"):
            rows.extend(_selector_rows(fl, depth, scope))
            continue
        type_word = _type_word(fl.get("value_schema"))
        if fl.get("unique"):
            type_word += " (unique)"
        prefix = f"Only with {scope}." if scope else ""
        rows.append([
            pad + _spelled_name(fl),
            _fmt_short(fl.get("short") or ""),
            type_word,
            _presence_cell(fl),
            fl.get("env") or "",
            _describe(fl, prefix),
        ])
    return rows


def _selector_rows(sel, depth, scope):
    """Rows for one selector flag and, indented under it, every choice scope."""
    rows = []
    pad = _INDENT * depth
    member_spelled = sel.get("elect_by") == "member-flags"
    choices = sel.get("choices") or []
    names = ", ".join(
        f"`--{c.get('name')}`" if member_spelled else f"`{c.get('name')}`"
        for c in choices
    )

    if member_spelled:
        # The name is the handler's key and the errors' noun, never a token.
        head_name = f"{pad}`{sel['name']}`"
        head_desc = (
            f"Selection (not typed as a flag). Elect exactly one of {names}."
        )
    else:
        head_name = f"{pad}`--{sel['name']} <choice>`"
        head_desc = f"Selection. Takes exactly one of {names}."
    prefix = f"Only with {scope}. " if scope else ""
    rows.append([
        head_name,
        _fmt_short(sel.get("short") or ""),
        "choice",
        _presence_cell(sel),
        sel.get("env") or "",
        (prefix + head_desc + (f" {sel['help']}" if sel.get("help") else "")),
    ])

    for choice in choices:
        cname = choice.get("name")
        scoped = list(choice.get("flags") or [])
        payload = None
        # A member-spelled choice's payload is the first scoped entry, under
        # the reserved name `value`: it is supplied by electing the member,
        # so it belongs on the member's own row rather than under it.
        if member_spelled and scoped and scoped[0].get("name") == "value":
            payload = scoped.pop(0)

        if member_spelled:
            token = f"`--{cname}`"
            type_word = _type_word((payload or {}).get("value_schema"))
            desc_parts = [f"Elects `{sel['name']}` = `{cname}`."]
            if choice.get("help"):
                desc_parts.append(choice["help"])
            if payload and payload.get("help"):
                desc_parts.append(f"Its value: {payload['help']}")
            choice_desc = " ".join(desc_parts)
            rows.append([
                _INDENT * (depth + 1) + token,
                "",
                type_word,
                # A member flag declares required, read as *required once
                # this member is elected*; the payload carries the same.
                _presence_cell(payload or choice) or "required",
                "",
                choice_desc,
            ])
            child_scope = token
        else:
            rows.append([
                _INDENT * (depth + 1) + f"`{cname}`",
                "",
                "",
                "",
                "",
                f"Value of `--{sel['name']}`."
                + (f" {choice.get('help')}" if choice.get("help") else ""),
            ])
            child_scope = f"`--{sel['name']} {cname}`"

        rows.extend(_flag_rows(scoped, depth + 2, child_scope))

    return rows


def _flag_table(flags):
    """Render the standard flag table for a list of schema flags."""
    return render_markdown_table(
        ["Name", "Short", "Type", "Presence", "Env", "Description"],
        _flag_rows(flags),
    )


def _arg_table(args):
    """Render the standard argument table for a list of schema args.

    Presence comes from the declaration, not from an assumption: the v1
    ``required`` key is deleted, and reading it with a ``True`` fallback --
    which is what this table did -- labelled every positional argument
    required whether it was or not.
    """
    rows = []
    for ar in args:
        type_word = _type_word(ar.get("value_schema"))
        if ar.get("variadic"):
            type_word += " (variadic)"
        desc = ar.get("help", "")
        note = _choices_note(ar)
        if note:
            desc = f"{desc} {note}".strip()
        rows.append([
            f"`{ar['name']}`", type_word, _presence_cell(ar), desc,
        ])
    return render_markdown_table(
        ["Name", "Type", "Presence", "Description"], rows,
    )


def iter_flag_tokens(flags):
    """Yield every ``--token`` an invocation can actually type, recursively.

    A member-spelled selector's own name is not among them -- it is never
    typed -- while each of its choices is, and a scoped flag is a token like
    any other.  This is what a completeness check must compare a page
    against; comparing against flag *names* would demand that a page
    document a token no user can write.
    """
    for fl in flags or []:
        if fl.get("elect_by"):
            if fl["elect_by"] == "selector-token":
                yield f"--{fl['name']}"
            for choice in fl.get("choices") or []:
                scoped = list(choice.get("flags") or [])
                if fl["elect_by"] == "member-flags":
                    yield f"--{choice.get('name')}"
                    if scoped and scoped[0].get("name") == "value":
                        scoped.pop(0)
                yield from iter_flag_tokens(scoped)
        else:
            yield f"--{fl['name']}"


def iter_flag_help(flags):
    """Yield ``(label, help)`` for every declaration a reader sees.

    Recurses through selector scopes, so a scoped flag's help is measured
    like any other.  A selector's own label is its bare name -- there is no
    ``--`` to print for a name that is never typed -- and each choice is
    labelled by the token that elects it.
    """
    for fl in flags or []:
        if fl.get("elect_by"):
            member_spelled = fl["elect_by"] == "member-flags"
            yield (fl["name"], fl.get("help", ""))
            for choice in fl.get("choices") or []:
                cname = choice.get("name")
                label = f"--{cname}" if member_spelled else cname
                yield (label, choice.get("help", ""))
                scoped = list(choice.get("flags") or [])
                if member_spelled and scoped and scoped[0].get("name") == "value":
                    payload = scoped.pop(0)
                    yield (f"--{cname} <value>", payload.get("help", ""))
                yield from iter_flag_help(scoped)
        else:
            yield (f"--{fl['name']}", fl.get("help", ""))


_CONSTRAINT_INTRO = {
    "at_least_one": "At least one of",
    "all_or_none": "All or none of",
}

_WHEN_WORDS = {
    "present": "when supplied",
    "true": "when true",
    "non_empty": "when non-empty",
}


def _member_text(member):
    """Render one constraint member: its resolved kind, name and election."""
    kind = member.get("kind")
    name = member.get("name", "")
    if kind == "arg":
        rendered = f"`{name}`"
    elif kind == "constraint":
        # A nested member has no election of its own -- the rule it names
        # carries one.
        return f"the `{name}` rule"
    else:
        rendered = f"`--{name}`"
    when = _WHEN_WORDS.get(member.get("when"))
    return f"{rendered} ({when})" if when else rendered


def _constraint_sentence(con):
    """Render one constraint as the rule it states."""
    kind = con.get("type")
    if kind in _CONSTRAINT_INTRO:
        members = ", ".join(_member_text(m) for m in con.get("members") or [])
        return f"{_CONSTRAINT_INTRO[kind]} {members}."
    if kind == "requires":
        return (
            f"`--{con.get('flag')}` requires `--{con.get('depends_on')}`."
        )
    if kind == "implies":
        value = _fmt_default(con.get("value"))
        return (
            f"`--{con.get('flag')}` implies `--{con.get('implies')}` = "
            f"{value}."
        )
    return str(kind)


def _constraints_lines(cmd, heading):
    """Return the constraints table lines for one command, or an empty list."""
    constraints = cmd.get("constraints") or []
    if not constraints:
        return []
    rows = [
        [f"`{con.get('name', '')}`", _constraint_sentence(con)]
        for con in constraints
    ]
    return [
        heading,
        "",
        "The framework enforces these before the command runs.",
        "",
        render_markdown_table(["Rule", "What it requires"], rows),
        "",
    ]


def _flag_sets_lines(cmd):
    """Return the flag-set grouping lines for one command, or an empty list.

    A command's flag-set members are merged into its flag list, so without
    this the grouping a project declared is invisible on the page.
    """
    sets = cmd.get("flag_sets") or []
    if not sets:
        return []
    lines = ["Flag sets:", ""]
    for fs in sets:
        members = ", ".join(f"`--{n}`" for n in fs.get("flags") or [])
        lines.append(f"- `{fs.get('name', '')}` -- {members}")
    lines.append("")
    return lines


def _update_lines(cmd):
    """Return the update-declaration lines for one command, or an empty list.

    ``update_of`` and ``write_mode`` are emitted together and never alone.
    The two facts a reader most needs are what an unsupplied property means
    and that at least one property is required, so both are stated outright.
    """
    update = cmd.get("update_of")
    if not update:
        return []
    write_mode = cmd.get("write_mode", "")
    arg_names = {a.get("name") for a in cmd.get("args") or []}

    def _ref(name):
        return f"`{name}`" if name in arg_names else f"`--{name}`"

    properties = update.get("properties") or []
    nullable_names = {
        fl["name"] for fl in cmd.get("flags") or [] if fl.get("nullable")
    }
    # Declaration order is the properties list's, not the flag list's.
    nullable = [n for n in properties if n in nullable_names]

    lines = [
        f"**Updates:** `{update.get('resource', '')}` "
        f"(write mode: {write_mode})",
        "",
    ]
    identity = update.get("identity") or []
    if identity:
        lines.append(
            "- Identified by: " + ", ".join(_ref(n) for n in identity)
        )
    lines.append(
        "- Writes: " + ", ".join(_ref(n) for n in properties)
        + " -- at least one of them is required."
    )
    if write_mode == "full_replace":
        lines.append(
            "- A property that is not supplied is re-sent as read, so every "
            "property is written."
        )
    else:
        lines.append("- A property that is not supplied is left unchanged.")
    if nullable:
        lines.append(
            "- Clearable: "
            + ", ".join(f"`--unset-{n}`" for n in nullable)
            + "."
        )
    lines.append("")
    return lines


def _config_lines(cli_structure):
    """Return the app-level configuration lines, or an empty list.

    Each of these keys is emitted only when the app departs from the
    framework's own behaviour, which is exactly what makes it worth a
    reader's attention.
    """
    rows = []
    if cli_structure.get("config"):
        rows.append([
            "Config file",
            "This app reads a config file; `--config <path>` selects one.",
        ])
    fmt = cli_structure.get("config_format")
    if fmt:
        rows.append(["Config format", f"`{fmt}`"])
    path = cli_structure.get("config_path")
    if path:
        rows.append(["Config path", _fmt_default(path)])
    mode = cli_structure.get("config_conflict_mode")
    if mode:
        rows.append([
            "Config conflict mode",
            f"`{mode}` (which source wins when both a CLI token and the "
            f"config file supply a value)",
        ])
    prefix = cli_structure.get("env_prefix")
    if prefix:
        rows.append([
            "Env prefix",
            f"`{prefix}` -- every env-bound flag reads `{prefix}` + its own "
            f"variable name unless it declares otherwise.",
        ])
    if not rows:
        return []
    return [
        "## Configuration",
        "",
        render_markdown_table(["Setting", "Value"], rows),
        "",
    ]


def _command_meta_lines(cmd):
    """Return the effect badge and dry-run refusal lines for one command.

    Empty for a pre-effects schema: ``effect`` is mandatory under the effects
    regime, so its absence means the app predates the regime and there is
    nothing honest to print.
    """
    lines = []
    effect = cmd.get("effect")
    if effect:
        badge = f"**Effect:** {effect}"
        if cmd.get("consequential"):
            badge += (
                " · **consequential** (prompts before running; "
                "`--approve-consequential` skips)"
            )
        lines.extend([badge, ""])

    # Emitted by strictcli only on a command that refuses --dry-run; absence
    # is the normal case (dry run works) and prints nothing.
    if cmd.get("dry_run_supported") is False:
        reason = cmd.get("dry_run_unsupported_reason", "")
        text = "**Dry run:** not supported"
        if reason:
            text += f" — {reason}"
        lines.extend([text, ""])

    return lines


def _grants_lines(cmd, heading):
    """Return the grants table lines for one command, or an empty list."""
    grants = cmd.get("grants") or []
    if not grants:
        return []
    rows = [
        [g.get("kind", ""), f"`{g.get('name', '')}`", g.get("reason", "")]
        for g in grants
    ]
    return [
        heading,
        "",
        render_markdown_table(["Kind", "Name", "Reason"], rows),
        "",
    ]


def _env_table(entries, description_header):
    """Render an infra env-var table (``env_var`` plus one other column)."""
    key = "default" if description_header == "Default" else "help"
    rows = [
        [f"`{e.get('env_var', '')}`", e.get(key, "") or ""]
        for e in entries
    ]
    return render_markdown_table(["Env var", description_header], rows)


def _render_command_page(cmd, app_name, nav_order, existing_path=None):
    """Render a Markdown page for a single command.

    If *existing_path* points to an existing page whose ``description``
    frontmatter has been hand-edited (i.e. is neither the current default
    -- the complete first sentence of the help -- nor a historical
    ``help[:155]`` truncation nor the long-form default template), that
    description is preserved instead of recomputing it.
    """
    name = cmd["name"]
    chelp = cmd.get("help", "")
    flags = cmd.get("flags", [])
    args = cmd.get("args", [])

    default_desc = compute_default_cli_description(
        "command", name, app_name, chelp,
    )

    existing_desc = None
    if existing_path is not None:
        existing_desc = _read_existing_cli_description(
            existing_path, kind="command", name=name, app_name=app_name,
            help_text=chelp,
        )
    cmd_desc = existing_desc if existing_desc is not None else default_desc
    seeded = existing_desc is None
    lines = [
        "---",
        f"title: {app_name} {name}",
        f'description: "{cmd_desc}"',
        "generated: true",
    ]
    if seeded:
        lines.append("seeded: true")
    lines.extend([
        'nav_group: "CLI Reference"',
        f"nav_order: {nav_order}",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} {name}",
        "",
    ])
    if chelp:
        lines.append(chelp)
        lines.append("")

    lines.extend(_command_meta_lines(cmd))
    lines.extend(_update_lines(cmd))

    if flags:
        lines.append("## Flags")
        lines.append("")
        lines.append(_flag_table(flags))
        lines.append("")
        lines.extend(_flag_sets_lines(cmd))

    if args:
        lines.append("## Arguments")
        lines.append("")
        lines.append(_arg_table(args))
        lines.append("")

    lines.extend(_constraints_lines(cmd, "## Constraints"))
    lines.extend(_grants_lines(cmd, "## Grants"))

    return "\n".join(lines)


def _render_group_page(grp, app_name, nav_order, existing_path=None):
    """Render a Markdown page for a command group and its subcommands.

    If *existing_path* points to an existing page whose ``description``
    frontmatter has been hand-edited (i.e. is neither the current default
    -- the complete first sentence of the help -- nor a historical
    ``help[:155]`` truncation nor the long-form default template), that
    description is preserved instead of recomputing it.
    """
    gname = grp["name"]
    ghelp = grp.get("help", "")
    subcmds = grp.get("commands", [])

    default_desc = compute_default_cli_description(
        "group", gname, app_name, ghelp,
    )

    existing_desc = None
    if existing_path is not None:
        existing_desc = _read_existing_cli_description(
            existing_path, kind="group", name=gname, app_name=app_name,
            help_text=ghelp,
        )
    grp_desc = existing_desc if existing_desc is not None else default_desc
    seeded = existing_desc is None
    lines = [
        "---",
        f"title: {app_name} {gname}",
        f'description: "{grp_desc}"',
        "generated: true",
    ]
    if seeded:
        lines.append("seeded: true")
    lines.extend([
        'nav_group: "CLI Reference"',
        f"nav_order: {nav_order}",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} {gname}",
        "",
    ])
    if ghelp:
        lines.append(ghelp)
        lines.append("")

    grp_deprecated = grp.get("deprecated") or {}
    if grp_deprecated:
        lines.append("## Deprecated")
        lines.append("")
        for dname in sorted(grp_deprecated):
            lines.append(f"- `{dname}` -- {grp_deprecated[dname]}")
        lines.append("")

    for cmd in subcmds:
        cname = cmd["name"]
        chelp = cmd.get("help", "")
        flags = cmd.get("flags", [])
        args = cmd.get("args", [])

        lines.append(f"## {gname} {cname}")
        lines.append("")
        if chelp:
            lines.append(chelp)
            lines.append("")

        lines.extend(_command_meta_lines(cmd))
        lines.extend(_update_lines(cmd))

        if flags:
            lines.append("### Flags")
            lines.append("")
            lines.append(_flag_table(flags))
            lines.append("")
            lines.extend(_flag_sets_lines(cmd))

        if args:
            lines.append("### Arguments")
            lines.append("")
            lines.append(_arg_table(args))
            lines.append("")

        lines.extend(_constraints_lines(cmd, "### Constraints"))
        lines.extend(_grants_lines(cmd, "### Grants"))

    return "\n".join(lines)


def _fmt_short(short):
    """Format a short flag for table display."""
    if short:
        return f"`-{short}`"
    return ""
