"""First-class support for strictcli-based projects.

Reads `.strictcli/schema.json` (generated by `<app> --dump-schema`) for CLI
structure (App, commands, flags, args, groups), and produces Markdown
documentation pages.
"""

import json
import os
import re

from selfdoc.utils import _read_project_field, parse_frontmatter as _parse_frontmatter
from selfdoc.tables import render_markdown_table
from selfdoc.utils import atomic_write as _atomic_write
from selfdoc_core.prose import first_sentence

from selfdoc_core import effects


# Matches the default per-command/per-group description templates so we can
# detect when a CLI page still has its auto-generated description (and should
# be recomputed) versus when a user has hand-edited the description (and we
# should preserve it).
#
# Templates produced by _render_command_page / _render_group_page when the
# command/group's help text is shorter than 50 characters:
#   "Reference for the {app_name} {name} command — usage, flags, arguments,
#    and examples for the {name} subcommand of the {app_name} CLI."
#   "Reference for the {app_name} {gname} command group — subcommands, flags,
#    arguments, and usage details for the {gname} group in the {app_name} CLI."
#
# And the CLI index template:
#   "Complete CLI reference for {app_name} — all available commands,
#    subcommands, flags, arguments, and usage examples with detailed
#    descriptions."
_DEFAULT_CLI_COMMAND_DESC_RE = re.compile(
    r"^Reference for the \S+ \S+ command — "
    r"usage, flags, arguments, and examples for the \S+ subcommand "
    r"of the \S+ CLI\.?$"
)
_DEFAULT_CLI_GROUP_DESC_RE = re.compile(
    r"^Reference for the \S+ \S+ command group — "
    r"subcommands, flags, arguments, and usage details "
    r"for the \S+ group in the \S+ CLI\.?$"
)
_DEFAULT_CLI_INDEX_DESC_RE = re.compile(
    r"^Complete CLI reference for \S+ — "
    r"all available commands, subcommands, flags, arguments, "
    r"and usage examples with detailed descriptions\.?$"
)


# ---------------------------------------------------------------------------
# Default description ownership (public: consumed by selfdoc.ownership)
# ---------------------------------------------------------------------------


def _normalize_cli_description(value):
    """Strip surrounding whitespace and one layer of matching quotes."""
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        value = value[1:-1].strip()
    return value


def compute_default_cli_description(kind, name, app_name, help_text):
    """Return the machine-default ``description`` for a CLI page.

    ``kind`` is ``"index"``, ``"command"``, or ``"group"``.  When the page's
    help text is long enough (>= 50 chars) the default is the first sentence
    of the help; otherwise a long-form template naming the app and command is
    used.  The index default is always the fixed long-form template.
    """
    if kind == "index":
        return (
            f"Complete CLI reference for {app_name} — "
            f"all available commands, subcommands, flags, arguments, "
            f"and usage examples with detailed descriptions."
        )
    if help_text and len(help_text) >= 50:
        return first_sentence(help_text)
    if kind == "command":
        return (
            f"Reference for the {app_name} {name} command — "
            f"usage, flags, arguments, and examples for the {name} subcommand "
            f"of the {app_name} CLI."
        )
    if kind == "group":
        return (
            f"Reference for the {app_name} {name} command group — "
            f"subcommands, flags, arguments, and usage details "
            f"for the {name} group in the {app_name} CLI."
        )
    raise ValueError(f"unknown CLI page kind: {kind!r}")


def is_default_cli_description(value, *, kind, name=None, app_name="",
                              help_text=None):
    """Return True if *value* is a machine-generated default CLI description.

    Recognizes every historical machine form so machine residue is reseeded
    rather than frozen as handwritten:

    - the current first-sentence form (help >= 50 chars), or
    - the long-form default template (help < 50 chars, or the index), or
    - the historical ``help[:155]`` truncation (with/without a trailing
      ellipsis), or
    - a >= 100-char prefix of the raw help (a truncated default from any
      prior cut point).

    An empty value counts as a machine default (a blank machine placeholder
    the caller should reseed).  CLI machine text is derivable from the schema,
    so this is a live recompute -- no static set can cover the truncated
    prefix family.
    """
    value = _normalize_cli_description(value)
    if not value:
        return True

    # Determine the "default_pattern" exactly as the renderers do so the
    # recognition matches what compute_default_cli_description emits.
    if kind == "index":
        default_pattern = _DEFAULT_CLI_INDEX_DESC_RE
    elif help_text and len(help_text) >= 50:
        default_pattern = first_sentence(help_text)
    elif kind == "command":
        default_pattern = _DEFAULT_CLI_COMMAND_DESC_RE
    elif kind == "group":
        default_pattern = _DEFAULT_CLI_GROUP_DESC_RE
    else:
        raise ValueError(f"unknown CLI page kind: {kind!r}")

    if hasattr(default_pattern, "match"):
        if default_pattern.match(value):
            return True
    elif value == default_pattern:
        return True

    if help_text and kind in ("command", "group"):
        core = value[:-3] if value.endswith("...") else value
        first_line = help_text.split("\n", 1)[0]
        if core == first_line[:155]:
            return True
        if len(core) >= 100 and help_text.startswith(core):
            return True

    return False


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------


def uses_strictcli(source_paths, base_dir):
    """Return True if the project has a ``.strictcli/schema.json`` file.

    The *source_paths* parameter is accepted for call-site compatibility
    but is not used -- detection is purely based on the schema file.
    """
    schema_path = os.path.join(base_dir, ".strictcli", "schema.json")
    return os.path.isfile(schema_path)


# ---------------------------------------------------------------------------
# Schema discovery
# ---------------------------------------------------------------------------


class SchemaDiscoveryError(RuntimeError):
    """Raised when ``.strictcli/schema.json`` discovery fails or is ambiguous.

    A hard error (exit 1). Subclasses ``RuntimeError`` so the CLI's existing
    ``RuntimeError`` handlers surface it with a clean message and non-zero exit.
    """


# Directory names never traversed when discovering schemas. Hidden directories
# (leading ``.``) are pruned separately -- ``.strictcli`` is not traversed into
# but is still detected as a schema *location* under each visited directory.
_SCHEMA_DISCOVERY_EXCLUDES: set[str] = {
    "node_modules", "dist", "build", "_build", "target",
    "vendor", "venv", "__pycache__",
}


def discover_schema_dirs(base_dir):
    """Discover directories containing a ``.strictcli/schema.json`` file.

    Walks *base_dir*, pruning vendored/build directories and hidden
    directories (leading ``.``). For every visited directory, checks whether it
    holds a ``.strictcli/schema.json`` and records its path relative to
    *base_dir* (the project root uses ``"."``).

    Returns a sorted list of relative directory paths (each is the directory
    that *contains* the ``.strictcli`` folder, i.e. the value a ``schema-dir``
    attribute would take).
    """
    base_dir = os.path.abspath(base_dir)
    found = []
    for dirpath, dirnames, _filenames in os.walk(base_dir):
        # Prune traversal into vendored/build and hidden directories.
        dirnames[:] = [
            d for d in dirnames
            if d not in _SCHEMA_DISCOVERY_EXCLUDES and not d.startswith(".")
        ]
        schema_path = os.path.join(dirpath, ".strictcli", "schema.json")
        if os.path.isfile(schema_path):
            rel = os.path.relpath(dirpath, base_dir)
            found.append("." if rel == os.curdir else rel)
    return sorted(found)


# ---------------------------------------------------------------------------
# Schema reader
# ---------------------------------------------------------------------------


def read_schema_json(base_dir, source_paths=None):
    """Read ``.strictcli/schema.json`` and translate to the internal format.

    Returns a dict with ``app_name``, ``app_version``, ``app_help``,
    ``commands`` (list), and ``groups`` (list) -- or ``None`` if the
    schema file does not exist.

    The translation preserves new fields from the schema (``choices``,
    ``hidden``, ``deprecated``, ``variadic``, ``passthrough``,
    ``repeatable``, ``negatable``) so downstream consumers can use them.
    """
    schema_path = os.path.join(base_dir, ".strictcli", "schema.json")
    if not os.path.isfile(schema_path):
        return None

    with open(schema_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    # Validate project_id
    project_id = schema.get("project_id")
    if project_id is None:
        app_name = schema.get("name", "<app>")
        raise ValueError(
            f"Schema missing project_id field. "
            f"Regenerate with: {app_name} --dump-schema"
        )
    expected = _read_project_field(base_dir, "name")
    if expected != "unknown" and project_id != expected:
        raise ValueError(
            f"Schema project_id '{project_id}' does not match "
            f"project name '{expected}'. Wrong schema file?"
        )

    result = {
        "app_name": schema.get("name", ""),
        "app_version": schema.get("version", ""),
        "app_help": schema.get("help", ""),
    }

    # Translate commands dict -> list
    commands_dict = schema.get("commands", {})
    result["commands"] = [
        _translate_command(name, cmd)
        for name, cmd in commands_dict.items()
    ]

    # Translate groups dict -> list (with nested commands dict -> list)
    groups_dict = schema.get("groups", {})
    result["groups"] = [
        _translate_group(name, grp)
        for name, grp in groups_dict.items()
    ]

    return result


def _translate_command(name, cmd):
    """Translate a schema command dict to the internal format."""
    translated = dict(cmd)
    # Ensure name is present
    translated.setdefault("name", name)
    return translated


def _translate_group(name, grp):
    """Translate a schema group dict to the internal format."""
    translated = {
        "name": grp.get("name", name),
        "help": grp.get("help", ""),
    }

    # Convert nested commands dict -> list
    commands_dict = grp.get("commands", {})
    translated["commands"] = [
        _translate_command(cname, cmd)
        for cname, cmd in commands_dict.items()
    ]

    # Preserve extra fields
    for key in ("deprecated", "groups"):
        if key in grp:
            translated[key] = grp[key]

    return translated


# ---------------------------------------------------------------------------
# Introspection
# ---------------------------------------------------------------------------


def extract_cli_structure(source_paths, base_dir):
    """Read the CLI structure from ``.strictcli/schema.json``.

    Returns a dict describing the app, its commands, flags, args, and
    groups -- or raises ``FileNotFoundError`` if no schema is found.

    The *source_paths* parameter is accepted for call-site compatibility
    but is not used.
    """
    result = read_schema_json(base_dir, source_paths=source_paths)
    if result is not None:
        return result
    raise FileNotFoundError(
        "No .strictcli/schema.json found in "
        f"{base_dir!r}. Run '<app> --dump-schema' to generate it."
    )


# ---------------------------------------------------------------------------
# Page generation
# ---------------------------------------------------------------------------


def expected_cli_page_filenames(cli_structure):
    """Return the list of filenames ``generate_cli_pages`` would write.

    Used by the stale-file cleanup pass to know which CLI page names are
    "current" so the generated pages from a prior run are not deleted as
    stale before the new pages have been written.
    """
    if cli_structure is None:
        return []
    names = ["cli-index.md"]
    for cmd in cli_structure.get("commands", []):
        names.append(f"cli-{cmd['name']}.md")
    for grp in cli_structure.get("groups", []):
        names.append(f"cli-{grp['name']}.md")
    return names


def _read_existing_cli_description(filepath, *, kind, name, app_name,
                                  help_text=None):
    """Return the hand-edited ``description`` from a CLI page, else ``None``.

    Returns ``None`` (meaning: reseed with the machine default) if the file
    does not exist, has no ``description`` key, has an empty description, or
    still holds a machine-generated default (recognized by
    :func:`is_default_cli_description`).  Any other value is a genuine hand
    edit and is returned verbatim.
    """
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except OSError:
        return None

    metadata, _ = _parse_frontmatter(content)
    raw = metadata.get("description")
    if raw is None or not isinstance(raw, str):
        return None

    value = _normalize_cli_description(raw)
    if not value:
        return None

    if is_default_cli_description(
        value, kind=kind, name=name, app_name=app_name, help_text=help_text,
    ):
        return None

    return value


def generate_cli_pages(cli_structure, docs_dir):
    """Generate Markdown documentation pages from *cli_structure*.

    Creates an index page and one page per top-level command group.
    All pages have ``generated: true`` frontmatter and read-only
    permissions (0o444).

    Returns a list of generated filenames (relative to *docs_dir*).
    """
    effects.makedirs(docs_dir, exist_ok=True)
    generated = []

    app_name = cli_structure.get("app_name", "")
    app_help = cli_structure.get("app_help", "")
    app_version = cli_structure.get("app_version", "")
    commands = cli_structure.get("commands", [])
    groups = cli_structure.get("groups", [])

    # -- Index page --
    default_index_desc = compute_default_cli_description(
        "index", None, app_name, None,
    )
    index_path = os.path.join(docs_dir, "cli-index.md")
    existing_index_desc = _read_existing_cli_description(
        index_path, kind="index", name=None, app_name=app_name,
    )
    cli_index_desc = (
        existing_index_desc
        if existing_index_desc is not None
        else default_index_desc
    )
    seeded_index = "seeded: true" if existing_index_desc is None else ""
    index_lines = [
        "---",
        f"title: {app_name} CLI Reference",
        f'description: "{cli_index_desc}"',
        "generated: true",
    ]
    if seeded_index:
        index_lines.append(seeded_index)
    index_lines.extend([
        'nav_group: "CLI Reference"',
        "nav_order: 0",
        "order: 91",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} CLI Reference",
        "",
    ])
    if app_help:
        index_lines.append(app_help)
        index_lines.append("")
    if app_version:
        # A var DIRECTIVE, not the literal version: the raw page body is what
        # staleness hashes, so baking the version in here moved the content
        # hash on every release and tripped STALE001 with zero signal.  The
        # directive resolves at build time, so the site still shows the
        # current version.
        index_lines.append('Version: :-: var key="project.version"')
        index_lines.append("")

    if commands:
        index_lines.append("## Commands")
        index_lines.append("")
        for cmd in commands:
            fname = f"cli-{cmd['name']}.html"
            index_lines.append(f"- [{cmd['name']}]({fname}) -- {cmd.get('help', '')}")
        index_lines.append("")

    if groups:
        index_lines.append("## Command Groups")
        index_lines.append("")
        for grp in groups:
            fname = f"cli-{grp['name']}.html"
            index_lines.append(f"- [{grp['name']}]({fname}) -- {grp.get('help', '')}")
        index_lines.append("")

    index_filename = "cli-index.md"
    _write_page(
        os.path.join(docs_dir, index_filename),
        "\n".join(index_lines),
    )
    generated.append(index_filename)

    # Build alphabetical ordering for all command/group pages
    all_names = sorted(
        [cmd["name"] for cmd in commands] + [grp["name"] for grp in groups]
    )
    name_to_nav_order = {name: idx + 1 for idx, name in enumerate(all_names)}

    # -- One page per top-level command --
    for cmd in commands:
        fname = f"cli-{cmd['name']}.md"
        out_path = os.path.join(docs_dir, fname)
        content = _render_command_page(
            cmd, app_name, name_to_nav_order[cmd["name"]],
            existing_path=out_path,
        )
        _write_page(out_path, content)
        generated.append(fname)

    # -- One page per group --
    for grp in groups:
        fname = f"cli-{grp['name']}.md"
        out_path = os.path.join(docs_dir, fname)
        content = _render_group_page(
            grp, app_name, name_to_nav_order[grp["name"]],
            existing_path=out_path,
        )
        _write_page(out_path, content)
        generated.append(fname)

    return generated


def _write_page(filepath, content):
    """Write a generated page atomically with read-only permissions."""
    _atomic_write(filepath, content, permissions=0o444)


def _render_command_page(cmd, app_name, nav_order, existing_path=None):
    """Render a Markdown page for a single command.

    If *existing_path* points to an existing page whose ``description``
    frontmatter has been hand-edited (i.e. is neither the current default
    -- the complete first sentence of the help -- nor a historical
    ``help[:155]`` truncation nor the long-form default template), that
    description is preserved instead of recomputing it.
    """
    name = cmd["name"]
    chelp = cmd.get("help", "")
    flags = cmd.get("flags", [])
    args = cmd.get("args", [])

    default_desc = compute_default_cli_description(
        "command", name, app_name, chelp,
    )

    existing_desc = None
    if existing_path is not None:
        existing_desc = _read_existing_cli_description(
            existing_path, kind="command", name=name, app_name=app_name,
            help_text=chelp,
        )
    cmd_desc = existing_desc if existing_desc is not None else default_desc
    seeded = existing_desc is None
    lines = [
        "---",
        f"title: {app_name} {name}",
        f'description: "{cmd_desc}"',
        "generated: true",
    ]
    if seeded:
        lines.append("seeded: true")
    lines.extend([
        'nav_group: "CLI Reference"',
        f"nav_order: {nav_order}",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} {name}",
        "",
    ])
    if chelp:
        lines.append(chelp)
        lines.append("")

    if flags:
        lines.append("## Flags")
        lines.append("")
        flag_rows = []
        for fl in flags:
            short = fl.get("short") or ""
            ftype = fl.get("type", "str")
            default = fl.get("default") or ""
            env = fl.get("env") or ""
            desc = fl.get("help", "")
            flag_rows.append([
                f"`--{fl['name']}`", _fmt_short(short), ftype, default, env, desc,
            ])
        lines.append(render_markdown_table(
            ["Name", "Short", "Type", "Default", "Env", "Description"],
            flag_rows,
        ))
        lines.append("")

    if args:
        lines.append("## Arguments")
        lines.append("")
        arg_rows = []
        for ar in args:
            req = "yes" if ar.get("required", True) else "no"
            arg_rows.append([f"`{ar['name']}`", req, ar.get("help", "")])
        lines.append(render_markdown_table(
            ["Name", "Required", "Description"],
            arg_rows,
        ))
        lines.append("")

    return "\n".join(lines)


def _render_group_page(grp, app_name, nav_order, existing_path=None):
    """Render a Markdown page for a command group and its subcommands.

    If *existing_path* points to an existing page whose ``description``
    frontmatter has been hand-edited (i.e. is neither the current default
    -- the complete first sentence of the help -- nor a historical
    ``help[:155]`` truncation nor the long-form default template), that
    description is preserved instead of recomputing it.
    """
    gname = grp["name"]
    ghelp = grp.get("help", "")
    subcmds = grp.get("commands", [])

    default_desc = compute_default_cli_description(
        "group", gname, app_name, ghelp,
    )

    existing_desc = None
    if existing_path is not None:
        existing_desc = _read_existing_cli_description(
            existing_path, kind="group", name=gname, app_name=app_name,
            help_text=ghelp,
        )
    grp_desc = existing_desc if existing_desc is not None else default_desc
    seeded = existing_desc is None
    lines = [
        "---",
        f"title: {app_name} {gname}",
        f'description: "{grp_desc}"',
        "generated: true",
    ]
    if seeded:
        lines.append("seeded: true")
    lines.extend([
        'nav_group: "CLI Reference"',
        f"nav_order: {nav_order}",
        "---",
        "<!-- generated by selfdoc gen (strictcli), do not edit -->",
        "",
        f"# {app_name} {gname}",
        "",
    ])
    if ghelp:
        lines.append(ghelp)
        lines.append("")

    for cmd in subcmds:
        cname = cmd["name"]
        chelp = cmd.get("help", "")
        flags = cmd.get("flags", [])
        args = cmd.get("args", [])

        lines.append(f"## {gname} {cname}")
        lines.append("")
        if chelp:
            lines.append(chelp)
            lines.append("")

        if flags:
            lines.append("### Flags")
            lines.append("")
            flag_rows = []
            for fl in flags:
                short = fl.get("short") or ""
                ftype = fl.get("type", "str")
                default = fl.get("default") or ""
                env = fl.get("env") or ""
                desc = fl.get("help", "")
                flag_rows.append([
                    f"`--{fl['name']}`", _fmt_short(short), ftype, default, env, desc,
                ])
            lines.append(render_markdown_table(
                ["Name", "Short", "Type", "Default", "Env", "Description"],
                flag_rows,
            ))
            lines.append("")

        if args:
            lines.append("### Arguments")
            lines.append("")
            arg_rows = []
            for ar in args:
                req = "yes" if ar.get("required", True) else "no"
                arg_rows.append([f"`{ar['name']}`", req, ar.get("help", "")])
            lines.append(render_markdown_table(
                ["Name", "Required", "Description"],
                arg_rows,
            ))
            lines.append("")

    return "\n".join(lines)


def _fmt_short(short):
    """Format a short flag for table display."""
    if short:
        return f"`-{short}`"
    return ""
