# strictspec document version gate (do not remove)
format_version = 1
bump = "patch"
include = ["npm", "pypi", "docs"]
exclude = []
candidate_sha = "c6202f87b04faae85b5196c9d2830c2d9b861b88"

[tree_hashes]
selfdoc = "edea53c14995dfe3dcfd28e5f8ade85c4dff647e"
